from src.algorithms.truncation_rules.Trunc3D_bayfill_xml import Trunc3D_bayfill
from src.algorithms.truncation_rules.Trunc2D_Angle_xml import Trunc2D_Angle
from src.algorithms.truncation_rules.Trunc2D_Cubic_xml import Trunc2D_Cubic
