from enum import Enum

from src.utils.constants.autogenerated import (
    BRANCH_NAME, BUILD_NUMBER, EXAMPLE_FOLDER, LATEST_COMMIT_HASH,
    LATEST_VERSION, LIBRARY_FOLDER,
)


def get_build_number() -> int:
    if BUILD_NUMBER:
        return int(BUILD_NUMBER)
    else:
        return -1


def get_path_to_example_files() -> str:
    return EXAMPLE_FOLDER


def get_commit_hash() -> str:
    return LATEST_COMMIT_HASH


def get_version_tag() -> str:
    if LATEST_VERSION:
        return f'version {LATEST_VERSION}'
    else:
        return f'build {get_build_number()}, on branch \'{BRANCH_NAME}\''


def get_path_to_libraries() -> str:
    return LIBRARY_FOLDER


class ExampleFiles(Enum):
    MODEL = get_path_to_example_files() + '/APS.xml'
    RMS = get_path_to_example_files() + '/rms_project_data_for_APS_gui.xml'


class DrawingLibrary(Enum):
    LIBRARY_PATH = get_path_to_libraries() + '/libdraw2D.so'
