image:
  name: "registry.git.equinor.com/aps/gui/aps-gui:5.0.0"

variables:
  GIT_STRATEGY:           "fetch"
  HTTP_PROXY:             "http://www-proxy.statoil.no:80"
  HTTPS_PROXY:            "http://www-proxy.statoil.no:80"
  FTP_PROXY:              "http://www-proxy.statoil.no:80"
  NO_PROXY:               "git.equinor.com"
  CODE_DIR:               "${CI_PROJECT_DIR}"
  ARTIFACTS:              "${CODE_DIR}/artifacts"
  MAKE:                   "make --directory=${CODE_DIR}"
  MKL_ROOT:               "/opt/intel/mkl"
  PYTHON:                 "${CODE_DIR}/.venv/bin/python"
  SHELL:                  "/bin/bash"
  PIPENV_VENV_IN_PROJECT: "1"
  DEPLOY_SERVER:          "tr-linrgsn001.tr.statoil.no"
  SYSTEM_INSTALL_PIPENV:  "yes"
  GIT_LFS_SKIP_SMUDGE:    "1"
  MATPLOTLIB_BACKEND:     "Agg"

stages:
  - init
  - check dependencies
  - testing
  - doc-tests  # https://docs.python.org/3/library/doctest.html
  - build gui
  - test gui
  - deploy
  - clean docker

before_script:
  - 'export PYTHONPATH="${CODE_DIR}:${PYTHONPATH}"'
  - 'export RMS_PYTHON="${RMS_PREFIX}/bin/LINUX_64/python"'

initialize:
  stage: init
  script:
    - 'export PYTHON="${RMS_PYTHON}"'
    - 'unset MAKE'
    - 'eval make --directory=${CODE_DIR} init'
    - 'eval rm -rf ${WORKON_HOME}/nrlib-*'
  artifacts:
    name: build-cache
    paths:
      - 'Pipfile'
      - 'Pipfile.lock'
      - '.venv/'
      - 'workflow/'
      - 'gui/node_modules'
    expire_in: 24 hours

vulnerabilities:
  stage: check dependencies
  script:
    - 'export PYTHON="$RMS_PYTHON"'
    - 'eval $MAKE initialize-python-environment'
    - 'eval $MAKE safety-check'
  allow_failure: true
  needs: []

JavaScript vulnerabilities:
  stage: check dependencies
  script:
    - 'eval $MAKE check-node-dependencies-for-vulnerabilities'
  needs:
    - job: initialize
      artifacts: true

outdated (Python) dependencies:
  stage: check dependencies
  script:
    - 'eval $MAKE check-requirements'
  allow_failure: true
  needs:
    - job: initialize
      artifacts: true

outdated (Node) dependencies:
  stage: check dependencies
  script:
    - 'eval $MAKE check-node-dependencies'
  allow_failure: true
  needs: []

circular dependencies:
  stage: check dependencies
  script:
    - 'eval $MAKE find-circular-dependencies'
  needs: []

linting (Python):
  stage: testing
  script:
    - 'eval $MAKE python-linting'
  allow_failure: true
  needs:
    - job: initialize
      artifacts: true

linting (JavaScript):
  stage: testing
  script:
    - 'eval $MAKE package.json'
    - 'eval $MAKE javascript-linting'
  needs:
    - job: initialize
      artifacts: true

unit testing:
  stage: testing  # https://github.com/ksator/continuous-integration-with-python
  script:
    - 'eval $MAKE unit-tests'
  dependencies:
    - initialize
  needs:
    - job: initialize
      artifacts: true

integration testing (RMS 11):
  stage: testing
  variables:
    WRITE_WORKFLOW_FILES_TO_PROJECT: "yes"
    RMS_PROJECT:                     "/integration_test/rms/model/testAPSWorkflow_new.rms11.1.2"
    APS_DEBUG_LEVEL:                 "4"
  script:
    - export PYTHON="$RMS_PYTHON"
    # tcpdump is useful to see which ports, and servers the firewall must be opened in order for RMS to talk with the
    # license server. Previously (in AWS), this information was available directly from DRM, but is no longer available.
    - yum install -y tcpdump  # TODO: Move to Docker image?
    - tcpdump -l -s 65535 > aps/unit_test/integration/data.pcap &
    - 'eval $MAKE integration-tests'
  artifacts:
    when: always
    name: logs
    paths:
      - 'aps/unit_test/integration/*.log'
      - 'aps/unit_test/integration/*.xml'
      - 'aps/unit_test/integration/*.dat'
      - 'aps/unit_test/integration/data.pcap'
    expire_in: 5 days
  needs: []

build GUI:
  stage: build gui
  script:
    - 'eval $MAKE build-gui'
  artifacts:
    expire_in: 1 month
    paths:
      - '*.plugin'
      - 'DEPLOY_VERSION.txt'
  needs:
    - job: initialize
      artifacts: true

.setup ssh keys:
  before_script:
    # Add the SSH key for cicd_aps
    # From https://docs.gitlab.com/ee/ci/ssh_keys/
    - 'eval $(ssh-agent -s)'
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - python -c 'import base64; import os; print(base64.b16decode(os.environ["CICD_APS_PRIVATE_KEY_HEX"]).decode("UTF-8"))' > ~/.ssh/id_rsa
    - ssh-add
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
  after_script:
    - rm -rf ~/.ssh


deploy release:
  stage: deploy
  extends: .setup ssh keys
  script:
    - 'eval $MAKE build-stable-gui'
    - 'eval $MAKE deploy-stable'
  only:
    - tags

update master:
  stage: deploy
  extends: .setup ssh keys
  script:
    - 'eval $MAKE update-remote-master'
  only:
    - master


deploy develop:
  stage: deploy
  extends: .setup ssh keys
  script:
    - 'eval $MAKE deploy update-remote-develop'
  dependencies:
    - build GUI
  only:
    - develop
