repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf

  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt
        language: system
        entry: mise run format:oxfmt

      - id: oxlint
        name: Lint GUI
        language: system
        pass_filenames: false
        entry: mise run lint:gui

  - repo: https://github.com/equinor/dependency-consistency
    rev: v2.1.2
    hooks:
      - id: consistent-dependencies
        args:
          - gui/yarn.lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args:
          - --fix
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: '^(bin/|aps/unit_test/integration).*\.sh$' # These will be dealt with in due time.

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt # prebuilt upstream executable
        args: ['-w', '-i', '4']
