repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf

  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt
        language: system
        entry: mise run format:oxfmt

      - id: oxlint
        name: Lint GUI
        language: node
        pass_filenames: false
        entry: mise run lint:gui
        additional_dependencies:
          - typescript@5.9.3
  #          - '@eslint/js@9.36.0'
  #          - '@stylistic/eslint-plugin@5.10.0'
  #          - '@vue/eslint-config-prettier@10.2.0'
  #          - '@vue/eslint-config-standard@9.0.1'
  #          - eslint@9.36.0
  #          - eslint-plugin-import@2.32.0
  #          - eslint-plugin-node@11.1.0
  #          - eslint-plugin-promise@7.3.0
  #          - eslint-plugin-security@3.0.1
  #          - eslint-plugin-vue@10.9.1
  #          - eslint-plugin-vuetify@2.7.2
  #          - vue-eslint-parser@10.4.1
  #          - globals@16.4.0

  - repo: https://github.com/equinor/dependency-consistency
    rev: v2.1.2
    hooks:
      - id: consistent-dependencies
        args:
          - gui/yarn.lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args:
          - --fix
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: '^(bin/|aps/unit_test/integration).*\.sh$' # These will be dealt with in due time.

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt # prebuilt upstream executable
        args: ['-w', '-i', '4']
