repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf

  - repo: local
    hooks:
      - id: prettier
        name: Prettier.js
        language: node
        additional_dependencies:
          - 'prettier@3.4.2'
        entry: prettier --write
        args:
          - --config=gui/.prettierrc
        types_or:
          [
            'javascript',
            'vue',
            'ts',
            'html',
            'css',
            'sass',
            'scss',
            'json',
            'yaml',
          ]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.1
    hooks:
      - id: eslint
        args:
          - --config=gui/eslint.config.cjs
          - --fix
        additional_dependencies:
          - '@eslint/js@9.36.0'
          - '@stylistic/eslint-plugin@5.4.0'
          - '@typescript-eslint/parser@8.45.0'
          - '@vue/eslint-config-prettier@10.2.0'
          - '@vue/eslint-config-standard@9.0.1'
          - '@vue/eslint-config-typescript@14.6.0'
          - eslint@9.36.0
          - eslint-plugin-import@2.32.0
          - eslint-plugin-node@11.1.0
          - eslint-plugin-promise@7.2.1
          - eslint-plugin-security@3.0.1
          - eslint-plugin-vue@10.5.0
          - eslint-plugin-vuetify@2.5.3
          - vue-eslint-parser@10.2.0
          - globals@16.4.0

  - repo: https://github.com/equinor/dependency-consistency
    rev: v2.1.2
    hooks:
      - id: consistent-dependencies
        args:
          - gui/yarn.lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args:
          - --fix
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: '^(bin/|aps/unit_test/integration).*\.sh$' # These will be dealt with in due time.

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt # prebuilt upstream executable
        args: ['-w', '-i', '4']
