services:
  api:
    build:
      context: .
      target: aps
      args:
        - RMS_IMAGE
    #      target: truncation-rules
    command:
      - 'roxenv'
      - 'poetry'
      - 'run'
      - 'python'
      - 'aps/api/app.py'
      - 'run'
      - '--host'
      - '0.0.0.0'
    environment:
      FLASK_DEBUG: '1'
      RMS_PROJECT_PATH: '${RMS_PROJECT_PATH}'
    volumes:
      - './aps:/code/aps'
      - './models/private:/private'
      - './models/project:/project'
    env_file:
      - .env

  web:
    build:
      context: .
      target: gui
    environment:
      NODE_ENV: development
      HOST: '0.0.0.0'
    volumes:
      - './gui/src:/code/src'
      - 'yarn-cache:/yarn'
      - 'node-cache:/code/node_modules/.cache'
    env_file:
      - gui/.env

  proxy:
    build:
      context: .
      target: server
    ports:
      - '8080:8080'
    volumes:
      - './nginx/local.nginx:/opt/bitnami/nginx/conf/server_blocks/local.conf:ro'
    depends_on:
      - web
      - api

volumes:
  yarn-cache:
  node-cache:
