PROJECT_NAME ?= aps-gui
SHELL := /bin/bash
OS ?= $(shell uname -s)
ifeq ($(OS),Linux)
NUMBER_OF_PROCESSORS := $(shell cat /proc/cpuinfo | grep processor | wc -l)
else  # Darwin
NUMBER_OF_PROCESSORS := $(shell sysctl -n hw.ncpu)
endif
LOG_DIR = logs
# Mode bay be 'production', or 'development'
MODE ?= production
# Valid options: TRACE, DEBUG, INFO (default), WARN, ERROR, CRITICAL
LOG_LEVEL = INFO
EXEC_NAME = app
MAIN_FILE = app.py
CODE_DIR ?= $(shell pwd)
LIB_DIR := $(CODE_DIR)/libs
PYTHONPATH := $(CODE_DIR):$(LIB_DIR):$(PYTHONPATH)
SOURCE_DIR = $(CODE_DIR)/src
BUILD_DIR = $(CODE_DIR)/build
LIB_PREFIX = $(CODE_DIR)/libraries
LIB_SOURCE := $(LIB_PREFIX)/sources
APSW_DIR := $(LIB_SOURCE)/apsw
LIBGAUSS_FIELD_PATH := $(LIB_PREFIX)/libgaussField
EXAMPLES_FOLDER = $(CODE_DIR)/examples
ENTRY_POINT = $(SOURCE_DIR)/gui/$(MAIN_FILE)
TEST_FOLDER = $(SOURCE_DIR)/unit_test
AUXILLARY = $(CODE_DIR)/auxillary
VULNERABILITY_DB = $(AUXILLARY)/vulnerability/data
PYTHON_LIBRARY_CONSTANT = $(SOURCE_DIR)/utils/constants/autogenerated.py
DOCKERFILE = $(CODE_DIR)/Dockerfile
DOCKER_REGISTRY_SERVER = git.statoil.no:4567
DOCKER_REGISTRY = $(DOCKER_REGISTRY_SERVER)/aps/gui
# Paths local to the compiled app
APP_EXAMPLES = ./examples
APP_LIBRARY = .
REQUESTS_CA_BUNDLE ?= $(SSL_CERT_FILE)
PYTHON ?= $(shell which python)
PIP ?= $(PYTHON) -m pip
PYTHON_PREFIX := $(shell dirname $(PYTHON))/..
IMAGE_VERSION ?= $(shell $(CODE_DIR)/bin/find-version-of-docker-image.py $(CODE_DIR))
IMAGE_NAME ?= $(PROJECT_NAME):$(IMAGE_VERSION)
DOCKER_IMAGE := $(DOCKER_REGISTRY)/$(IMAGE_NAME)
PIPENV := $(PYTHON) -m pipenv
RUN := $(PIPENV) run
PY.TEST := $(RUN) python -m pytest
PYLINT := $(RUN) pylint
SAFETY_CHECK := $(PIPENV) check
PYREVERSE := $(RUN) pyreverse
PIPROT := $(RUN) piprot

MKDIR := mkdir -p
TAR := tar
TAR_EXCRACT := $(TAR) -xf

# NRlib
BUILD_NRLIB ?= no
ifeq ($(BUILD_NRLIB),yes)
NRLIB := install-nrlib
TEST_NRLIB := test-nrlib
else
NRLIB :=
TEST_NRLIB :=
endif
NRLIB_URL_HTTPS := https://gitlab-ci-token:$(CI_BUILD_TOKEN)@git.statoil.no/SDP/nrlib.git
NRLIB_URL_SSH := git@git.statoil.no:SDP/nrlib.git
NRLIB_PATH := $(LIB_SOURCE)/nrlib
NRLIB_VERSION ?= 1.1-r5

# APSW (Another Python SQLite Wrapper)
# Build options
BUILD_APSW ?= no
FETCH_APSW_SQLITE ?= yes

APSW_DEBUG := $(shell [[ $(MODE) -eq "development" ]] && echo "--debug" || echo "")
SQLITE_VERSION := 3.22.0
APSW_VERSION := $(SQLITE_VERSION)-r1

APSW :=
FETCH_SQLITE :=
ifeq ($(BUILD_APSW),yes)
APSW := install-apsw
ifeq ($(FETCH_APSW_SQLITE),yes)
FETCH_SQLITE := fetch --version $(SQLITE_VERSION) --all
endif
endif

define AUTOGENERATED_CONSTANTS
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This file is automatically created from make (make empty-constants)
"""
__author__ = "Sindre Nistad"
__email__ = "snis@statoil.com"
__version__ = "0.1.0"
__status__ = "testing"

# --Values--
LATEST_COMMIT_HASH = '$(shell git rev-parse --short HEAD)'
LATEST_VERSION = '$(shell git describe --all | grep -E v[0-9]+\.[0-9]+\.[0-9]+ | tr -d 'v')'
BUILD_NUMBER = '$(shell git rev-list --count HEAD 2>/dev/null || git rev-list --all | wc -l)'
BRANCH_NAME = '$(shell git rev-parse --abbrev-ref HEAD)'

# --Paths--
# Local to the machine
LIBRARY_FOLDER = '$(LIB_PREFIX)'
EXAMPLE_FOLDER = '$(EXAMPLES_FOLDER)'
# In the compiled app
LIBRARY_FOLDER_APP = '$(APP_LIBRARY)'
EXAMPLE_FOLDER_APP = '$(APP_EXAMPLES)'
endef
export AUTOGENERATED_CONSTANTS

COLOR = \033[32;01m
NO_COLOR = \033[0m
.PHONY: help run

# Build / clean / run
build:

init: initialize-python-environment dependencies autogenerated-constants links generate-workflow-files

links: create-workflow-dir
	ln -sf $(CODE_DIR)/depricated/APS_make_gauss_IPL.py $(CODE_DIR)/bin
	ln -sf $(CODE_DIR)/depricated/APSGaussFieldJobs.py $(SOURCE_DIR)/algorithms
	ln -sf $(CODE_DIR)/depricated/APSupdateVarioAsimuth.py $(SOURCE_DIR)/utils
	ln -sf $(CODE_DIR)/depricated/getRMSProjectData.py $(SOURCE_DIR)/utils/roxar
	ln -sf $(CODE_DIR)/depricated/DefineTruncStructure.py $(CODE_DIR)/examples
	ln -sf $(CODE_DIR)/depricated/to_be_deleted/APS_simulate_gauss_multiprocessing.ipl $(CODE_DIR)/workflow
	ln -sf $(CODE_DIR)/depricated/to_be_deleted/Cleanup_tmpdir.ipl $(CODE_DIR)/workflow
	ln -sf $(CODE_DIR)/workflow/APS_simulate_gauss_multiprocessing.py $(CODE_DIR)/bin
	ln -sf $(CODE_DIR)/workflow/APS_simulate_gauss_singleprocessing.py $(CODE_DIR)/bin
	ln -sf $(CODE_DIR)/src/utils/ConvertBitMapToRMS.py $(CODE_DIR)/workflow

create-workflow-dir:
	$(MKDIR) $(CODE_DIR)/workflow

clean-links:
	rm -f $(CODE_DIR)/bin/APS_make_gauss_IPL.py
	rm -f $(SOURCE_DIR)/algorithms/depricated/APSGaussFieldJobs.py
	rm -f $(SOURCE_DIR)/utils/APSupdateVarioAsimuth.py
	rm -f $(SOURCE_DIR)/utils/roxar/getRMSProjectData.py
	rm -f $(CODE_DIR)/examples/DefineTruncStructure.py
	rm -f $(CODE_DIR)/workflow/APS_simulate_gauss_multiprocessing.ipl
	rm -f $(CODE_DIR)/workflow/Cleanup_tmpdir.ipl
	rm -f $(CODE_DIR)/bin/APS_simulate_gauss_multiprocessing.py
	rm -f $(CODE_DIR)/bin/APS_simulate_gauss_singleprocessing.py
	rm -f $(CODE_DIR)/workflow/ConvertBitMapToRMS.py

generate-workflow-files: create-workflow-dir
	$(PYTHON) $(CODE_DIR)/bin/generate_workflow_blocks.py $(CODE_DIR)

dependencies: libdraw2D.so nrlib requirements $(TEST_NRLIB) apsw

nrlib: $(NRLIB)

install-nrlib: get-nrlib
	cd $(NRLIB_PATH) && \
	CODE_DIR=$(NRLIB_PATH) \
	make build-boost-python

test-nrlib:
	$(PY.TEST) $(NRLIB_PATH)/tests

get-nrlib:
	$(MKDIR) $(NRLIB_PATH)
	curl https://git.statoil.no/sdp/nrlib/repository/v$(NRLIB_VERSION)/archive.tar.gz \
	     --output nrlib-$(NRLIB_VERSION).tar.gz \
	     --silent
	$(TAR_EXCRACT) nrlib-$(NRLIB_VERSION).tar.gz -C $(NRLIB_PATH) --strip-components=1
	rm nrlib-$(NRLIB_VERSION).tar.gz

initialize-python-environment:
	cd $(CODE_DIR) && \
	{ $(PIPENV) --venv || $(PIPENV) --python=$(PYTHON) --site-packages ; }

requirements:
	cd $(CODE_DIR) && \
	$(PIPENV) install --dev

apsw: $(APSW)

install-apsw: compile-apsw library-directory
	$(shell mv `find $(APSW_DIR) -name apsw*.so` $(LIB_DIR)/apsw.so)

compile-apsw: get-apsw
	# TODO?: Add $(APSW_DEBUG) again?
	cd $(APSW_DIR) && \
	CFLAGS="-std=c11" \
	$(PYTHON) setup.py $(FETCH_SQLITE) \
                       build --enable-all-extensions \
                       build_ext --force --inplace \
                       test

get-apsw:
	$(MKDIR) $(APSW_DIR) && \
	wget https://github.com/rogerbinns/apsw/archive/$(APSW_VERSION).tar.gz --output-document=$(LIB_PREFIX)/apsw-$(APSW_VERSION).tar.gz && \
	$(TAR_EXCRACT) $(LIB_PREFIX)/apsw-$(APSW_VERSION).tar.gz -C $(APSW_DIR) --strip-components=1 && \
	rm -f $(LIB_PREFIX)/apsw-$(APSW_VERSION).tar.gz

# Build libgaussField
libdraw2D.so: autogenerated-constants library-directory
	cd $(LIBGAUSS_FIELD_PATH) && \
	CODE_DIR=$(LIBGAUSS_FIELD_PATH) \
	  make build && \
	  mv $(LIBGAUSS_FIELD_PATH)/libdraw2D.so $(LIB_DIR)

library-directory:
	$(MKDIR) $(LIB_DIR)

autogenerated-constants:
	echo "$$AUTOGENERATED_CONSTANTS" > $(PYTHON_LIBRARY_CONSTANT)

clean-autogrenerated:
	rm -f $(PYTHON_LIBRARY_CONSTANT)

clean: clean-autogrenerated clean-links clean-workflow-blocks
	rm -rf $(BUILD_DIR)
	rm -f $(LIBGAUSS_FIELD_PATH)/*.o
	rm -f  $(EXEC_NAME).spec
	rm -f $(CODE_DIR)/build.txt

clean-workflow-blocks:
	rm -rf $(CODE_DIR)/workflow

clean-app:
	rm -rf $(EXEC_NAME)

clean-all: clean clean-tests clean-cache clean-nrlib

clean-nrlib: uninstall-nrlib remove-nrlib-source

remove-nrlib-source:
	rm -rf $(NRLIB_PATH)
	rm -f nrlib-$(NRLIB_VERSION).tar.gz

uninstall-nrlib:
	$(PIPENV) uninstall nrlib

clean-cache: clean-__pycache__ clean-pyc

clean-__pycache__:
	rm -rf $(shell find $(SOURCE_DIR) -name __pycache__)

clean-pyc:
	rm -f $(shell find $(SOURCE_DIR) -name *.pyc)

docker-image:
	docker build --rm --pull --tag $(DOCKER_IMAGE) --file $(DOCKERFILE) $(CODE_DIR)

docker-login:
	docker login $(DOCKER_REGISTRY_SERVER)
	# TODO: Add new user / bot to gitlab

docker-push-image: docker-image
	docker push $(DOCKER_IMAGE)

docker-bash:
	docker run --rm -it -v $(CODE_DIR):/code --workdir=/code $(DOCKER_IMAGE) bash


copy-source:
	$(TAR) --exclude='$(CODE_DIR)/.git/' --exclude="$(CODE_DIR)/documentation" -cvzf code.tar.gz *

check-requirements:
	$(PIPENV) lock --dev --requirements | $(PIPROT) --outdated -

safety-check:
	$(PIPENV) check

unit-tests: run-tests clean-tests

run-tests: links
	cd $(TEST_FOLDER) && \
	$(PY.TEST) --basetemp=$(TEST_FOLDER)

clean-tests:
	rm -rf $(TEST_FOLDER)/.cache && \
	rm -f  $(TEST_FOLDER)/*.dat  && \
	rm -f  $(TEST_FOLDER)/*.xml && \
	rm -f  $(TEST_FOLDER)/libdraw2D.so

# TODO: Add diagrams for Previewer, and other files / classes of interest
uml-diagrams: uml-main-program

uml-main-program:
	cd $(CODE_DIR) && \
	$(PYREVERSE) -ASmy -k -o png $(ENTRY_POINT) -p APS-GUI

linting:
	$(PYLINT) --jobs=$(NUMBER_OF_PROCESSORS) $(SOURCE_DIR) $(CODE_DIR)/depricated $(CODE_DIR)/bin

print-%  : ; @echo $($*)
