PROJECT_NAME ?= aps-gui
SHELL := /bin/bash
OS ?= $(shell uname -s)
ifeq ($(OS),Linux)
NUMBER_OF_PROCESSORS := $(shell cat /proc/cpuinfo | grep processor | wc -l)
else  # Darwin
NUMBER_OF_PROCESSORS := $(shell sysctl -n hw.ncpu)
endif
LOG_DIR = logs
# Valid options: TRACE, DEBUG, INFO (default), WARN, ERROR, CRITICAL
LOG_LEVEL = INFO
EXEC_NAME = app
MAIN_FILE = app.py
CODE_DIR ?= $(shell pwd)
PYTHONPATH := $(CODE_DIR):$(PYTHONPATH)
SOURCE_DIR = $(CODE_DIR)/src
BUILD_DIR = $(CODE_DIR)/build
LIB_PREFIX = $(CODE_DIR)/libraries
LIBGAUSS_FIELD_PATH := $(LIB_PREFIX)/libgaussField
EXAMPLES_FOLDER = $(CODE_DIR)/examples
ENTRY_POINT = $(SOURCE_DIR)/gui/$(MAIN_FILE)
TEST_FOLDER = $(SOURCE_DIR)/unit_test
AUXILLARY = $(CODE_DIR)/auxillary
VULNERABILITY_DB = $(AUXILLARY)/vulnerability/data
PYTHON_LIBRARY_CONSTANT = $(SOURCE_DIR)/utils/constants/autogenerated.py
DOCKERFILE = $(CODE_DIR)/Dockerfile
DOCKER_REGISTRY_SERVER = git.statoil.no:4567
DOCKER_REGISTRY = $(DOCKER_REGISTRY_SERVER)/aps/gui
# Paths local to the compiled app
APP_EXAMPLES = ./examples
APP_LIBRARY = .
PYTHON ?= $(shell which python)
PIP ?= $(PYTHON) -m pip
PYTEST := $(PYTHON) -m pytest
PIPROT := $(PYTHON) -m piprot
PYLINT := $(PYTHON) -m pylint
SAFETY_CHECK := $(PYTHON) -m safety check
PYREVERSE := $(PYTHON) -m pyreverse
PYTHON_PREFIX := $(shell dirname $(PYTHON))/..
IMAGE_VERSION ?= $(shell $(CODE_DIR)/bin/find-version-of-docker-image.sh $(CODE_DIR))
IMAGE_NAME ?= $(PROJECT_NAME):$(IMAGE_VERSION)

# NRlib
BUILD_NRLIB ?= no
ifeq ($(BUILD_NRLIB),yes)
NRLIB := install-nrlib
else
NRLIB :=
endif
NRLIB_URL_HTTPS := https://gitlab-ci-token:$(CI_BUILD_TOKEN)@git.statoil.no/SDP/nrlib.git
NRLIB_URL_SSH := git@git.statoil.no:SDP/nrlib.git
NRLIB_PATH := $(LIB_PREFIX)/nrlib
NRLIB_VERSION ?= 1.0a

# APSW (Another Python SQLite Wrapper)
BUILD_ASPW ?= no
ifeq ($(BUILD_APSW),yes)
APWS := get-apsw install-apsw
else
APWS :=
endif
APSW_VERSION := 3.21.0-r1
APSW_DIR := $(LIB_PREFIX)/build/apsw-$(APSW_VERSION)

define AUTOGENERATED_CONSTANTS
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This file is automatically created from make (make empty-constants)
"""
__author__ = "Sindre Nistad"
__email__ = "snis@statoil.com"
__version__ = "0.1.0"
__status__ = "testing"

# --Values--
LATEST_COMMIT_HASH = '$(shell git rev-parse --short HEAD)'
LATEST_VERSION = '$(shell git describe --all | grep -E v[0-9]+\.[0-9]+\.[0-9]+ | tr -d 'v')'
BUILD_NUMBER = '$(shell git rev-list --count HEAD 2>/dev/null || git rev-list --all | wc -l)'
BRANCH_NAME = '$(shell git rev-parse --abbrev-ref HEAD)'

# --Paths--
# Local to the machine
LIBRARY_FOLDER = '$(LIB_PREFIX)'
EXAMPLE_FOLDER = '$(EXAMPLES_FOLDER)'
# In the compiled app
LIBRARY_FOLDER_APP = '$(APP_LIBRARY)'
EXAMPLE_FOLDER_APP = '$(APP_EXAMPLES)'
endef
export AUTOGENERATED_CONSTANTS

COLOR = \033[32;01m
NO_COLOR = \033[0m
.PHONY: help run

# Build / clean / run
build: clean-all init

init: dependencies autogenerated-constants links generate-workflow-files

links: create-workflow-dir
	ln -sf $(CODE_DIR)/depricated/APS_make_gauss_IPL.py $(CODE_DIR)/bin
	ln -sf $(CODE_DIR)/depricated/APSGaussFieldJobs.py $(SOURCE_DIR)/algorithms
	ln -sf $(CODE_DIR)/depricated/APSupdateVarioAsimuth.py $(SOURCE_DIR)/utils
	ln -sf $(CODE_DIR)/depricated/getRMSProjectData.py $(SOURCE_DIR)/utils/roxar
	ln -sf $(CODE_DIR)/depricated/DefineTruncStructure.py $(CODE_DIR)/examples
	ln -sf $(CODE_DIR)/depricated/to_be_deleted/APS_simulate_gauss_multiprocessing.ipl $(CODE_DIR)/workflow
	ln -sf $(CODE_DIR)/depricated/to_be_deleted/Cleanup_tmpdir.ipl $(CODE_DIR)/workflow
	ln -sf $(CODE_DIR)/workflow/APS_simulate_gauss_multiprocessing.py $(CODE_DIR)/bin
	ln -sf $(CODE_DIR)/workflow/APS_simulate_gauss_singleprocessing.py $(CODE_DIR)/bin
	ln -sf $(CODE_DIR)/src/utils/ConvertBitMapToRMS.py $(CODE_DIR)/workflow

create-workflow-dir:
	mkdir -p $(CODE_DIR)/workflow

clean-links:
	rm -f $(CODE_DIR)/bin/APS_make_gauss_IPL.py
	rm -f $(SOURCE_DIR)/algorithms/depricated/APSGaussFieldJobs.py
	rm -f $(SOURCE_DIR)/utils/APSupdateVarioAsimuth.py
	rm -f $(SOURCE_DIR)/utils/roxar/getRMSProjectData.py
	rm -f $(CODE_DIR)/examples/DefineTruncStructure.py
	rm -f $(CODE_DIR)/workflow/APS_simulate_gauss_multiprocessing.ipl
	rm -f $(CODE_DIR)/workflow/Cleanup_tmpdir.ipl
	rm -f $(CODE_DIR)/bin/APS_simulate_gauss_multiprocessing.py
	rm -f $(CODE_DIR)/bin/APS_simulate_gauss_singleprocessing.py
	rm -f $(CODE_DIR)/workflow/ConvertBitMapToRMS.py

generate-workflow-files: create-workflow-dir
	$(PYTHON) $(CODE_DIR)/bin/generate_workflow_blocks.py $(CODE_DIR)

dependencies: libdraw2D.so requirements nrlib apsw

nrlib: $(NRLIB)

install-nrlib: clean-nrlib get-nrlib
	cd $(NRLIB_PATH) && \
	CODE_DIR=$(NRLIB_PATH) \
	make build && \
	make install && \
	make tests

get-nrlib:
	mkdir -p $(NRLIB_PATH)
	curl https://git.statoil.no/sdp/nrlib/repository/v$(NRLIB_VERSION)/archive.tar.gz \
	     --output nrlib-$(NRLIB_VERSION).tar.gz \
	     --silent
	tar -xvf nrlib-$(NRLIB_VERSION).tar.gz -C $(NRLIB_PATH) --strip-components=1
	rm nrlib-$(NRLIB_VERSION).tar.gz

requirements:
	$(PIP) install -r $(CODE_DIR)/requirements.txt || $(PIP) install --user -r $(CODE_DIR)/requirements.txt

apsw: $(APSW)

install-apsw:
	cd $(APSW_DIR) && \
	$(PYTHON) setup.py fetch && \
	$(PYTHON) setup.py build --enable-all-extensions && \
	$(PYTHON) setup.py install && \
	$(PYTHON) setup.py test && \
	rm -rf $(APSW_DIR)

get-apsw:
	mkdir -p $(APSW_DIR) $(LIB_PREFIX)/source && \
	wget https://github.com/rogerbinns/apsw/archive/$(APSW_VERSION).tar.gz --output-document=$(LIB_PREFIX)/source/apsw-$(APSW_VERSION).tar.gz && \
	tar -xvf $(LIB_PREFIX)/source/apsw-$(APSW_VERSION).tar.gz -C $(APSW_DIR) --strip-components=1 && \
	rm -f $(LIB_PREFIX)/source/apsw-$(APSW_VERSION).tar.gz

# Build libgaussField
libdraw2D.so: autogenerated-constants
	cd $(LIBGAUSS_FIELD_PATH) && \
	CODE_DIR=$(LIBGAUSS_FIELD_PATH) \
	  make build && \
	  mv $(LIBGAUSS_FIELD_PATH)/libdraw2D.so $(LIB_PREFIX)

autogenerated-constants:
	echo "$$AUTOGENERATED_CONSTANTS" > $(PYTHON_LIBRARY_CONSTANT)

clean-autogrenerated:
	rm -f $(PYTHON_LIBRARY_CONSTANT)

clean: clean-autogrenerated clean-links clean-workflow-blocks
	rm -rf $(BUILD_DIR)
	rm -f $(LIBGAUSS_FIELD_PATH)/*.o
	rm -f  $(EXEC_NAME).spec
	rm -f $(CODE_DIR)/build.txt

clean-workflow-blocks:
	rm -rf $(CODE_DIR)/workflow

clean-app:
	rm -rf $(EXEC_NAME)

clean-all: clean clean-safety clean-tests clean-cache clean-nrlib

clean-nrlib:
	$(PIP) uninstall --yes nrlib || echo "NRlib has not been installed"
	rm -rf $(NRLIB_PATH)
	rm -f nrlib-$(NRLIB_VERSION).tar.gz

clean-cache: clean-__pycache__ clean-pyc

clean-__pycache__:
	rm -rf $(shell find $(SOURCE_DIR) -name __pycache__)

clean-pyc:
	rm -f $(shell find $(SOURCE_DIR) -name *.pyc)

docker-image:
	docker build --rm --pull --tag $(DOCKER_REGISTRY)/$(IMAGE_NAME) --file $(DOCKERFILE) $(CODE_DIR)

docker-login:
	docker login $(DOCKER_REGISTRY_SERVER)
	# TODO: Add new user / bot to gitlab

docker-push-image: docker-image
	docker push $(DOCKER_REGISTRY)/$(IMAGE_NAME)

copy-source:
	tar --exclude='$(CODE_DIR)/.git/' --exclude="$(CODE_DIR)/documentation" -cvzf code.tar.gz *

check-requirements:
	$(PIPROT) --outdated $(CODE_DIR)/requirements.txt

safety-check: clean-safety get-vulnerability-db
	$(SAFETY_CHECK) --full-report --db $(VULNERABILITY_DB)

get-vulnerability-db:
	mkdir -p $(VULNERABILITY_DB) && \
    for file in 'insecure.json' 'insecure_full.json' ; do \
        curl --proxy $(HTTP_PROXY) \
             --output $(VULNERABILITY_DB)/$$file \
             https://raw.githubusercontent.com/pyupio/safety-db/master/data/$$file; \
    done

clean-safety:
	rm -rf $(VULNERABILITY_DB)

unit-tests: dependencies copy-libdraw-to-test run-tests clean-tests

copy-libdraw-to-test: libdraw2D.so

run-tests: links
	cd $(TEST_FOLDER) && \
	$(PYTEST) --basetemp=$(TEST_FOLDER)

clean-tests:
	rm -rf $(TEST_FOLDER)/.cache && \
	rm -f  $(TEST_FOLDER)/*.dat  && \
	rm -f  $(TEST_FOLDER)/*.xml && \
	rm -f  $(TEST_FOLDER)/libdraw2D.so

# TODO: Add diagrams for Previewer, and other files / classes of interest
uml-diagrams:
	cd $(CODE_DIR) && \
	$(PYREVERSE) -ASmy -k -o png $(ENTRY_POINT) -p APS-GUI

linting:
	$(PYLINT) --jobs=$(NUMBER_OF_PROCESSORS) $(SOURCE_DIR) $(CODE_DIR)/depricated $(CODE_DIR)/bin

print-%  : ; @echo $($*)
