PROJECT_NAME ?= aps-gui
SHELL := /bin/bash
LOG_DIR = logs
# Valid options: TRACE, DEBUG, INFO (default), WARN, ERROR, CRITICAL
LOG_LEVEL = INFO
EXEC_NAME = app
MAIN_FILE = app.py
ifeq ($(CODE_DIR),)
CODE_DIR := $(shell pwd)
endif
ifeq ($(PYTHONPATH),)
PYTHONPATH := $(CODE_DIR)
endif
SOURCE_DIR = $(CODE_DIR)/src
BUILD_DIR = $(CODE_DIR)/build
LIB_PREFIX = $(CODE_DIR)/libraries
EXAMPLES_FOLDER = $(CODE_DIR)/examples
ENTRY_POINT = $(SOURCE_DIR)/gui/$(MAIN_FILE)
TEST_FOLDER = $(SOURCE_DIR)/unit_test
AUXILLARY = $(CODE_DIR)/auxillary
VULNERABILITY_DB = $(AUXILLARY)/vulnerability/data
PYTHON_LIBRARY_CONSTANT = $(SOURCE_DIR)/utils/constants/autogenerated.py
DOCKERFILE = Dockerfile
GCC_VERSION = 4.9.4
DOCKER_REGISTRY_SERVER = git.statoil.no:4567
DOCKER_REGISTRY = $(DOCKER_REGISTRY_SERVER)/aps/gui
# Paths local to the compiled app
APP_EXAMPLES = ./examples
APP_LIBRARY = .
ifeq ($(PIP),)
PIP := $(shell which pip)
endif
ifeq ($(UPX_DIR),)
UPX_DIR := $(shell dirname $(shell which upx) 2>/dev/null || echo "")
endif
ifeq ($(IMAGE_VERSION),)
IMAGE_VERSION := $(shell ./bin/find-version-of-docker-image.sh $(CODE_DIR))
endif
ifeq ($(IMAGE_NAME),)
IMAGE_NAME := $(PROJECT_NAME):$(IMAGE_VERSION)
endif
ifeq ($(LIB_GL),)
LIB_GL := $(shell echo "$(shell ldconfig -p | grep libGL.so.1 | tr ' ' '\n' | grep /)")
endif
define AUTOGENERATED_CONSTANTS
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This file is automatically created from make (make empty-constants)
"""

# --Values--
LATEST_COMMIT_HASH = '$(shell git rev-parse --short HEAD)'
LATEST_VERSION = '$(shell git describe --all | grep -E v[0-9]+\.[0-9]+\.[0-9]+ | tr -d 'v')'
BUILD_NUMBER = '$(shell git rev-list --count HEAD 2>/dev/null || git rev-list --all | wc -l)'
BRANCH_NAME = '$(shell git rev-parse --abbrev-ref HEAD)'

# --Paths--
# Local to the machine
LIBRARY_FOLDER = '$(LIB_PREFIX)'
EXAMPLE_FOLDER = '$(EXAMPLES_FOLDER)'
# In the compiled app
LIBRARY_FOLDER_APP = '$(APP_LIBRARY)'
EXAMPLE_FOLDER_APP = '$(APP_EXAMPLES)'
endef
export AUTOGENERATED_CONSTANTS

COLOR = \033[32;01m
NO_COLOR = \033[0m
.PHONY: help run

# Build / clean / run
build: clean-all

# Build libgaussField
libdraw2D.so: autogenerated-constants
	cd $(LIB_PREFIX) && \
	./buildSharedLib.sh -O3

autogenerated-constants:
	echo "$$AUTOGENERATED_CONSTANTS" > $(PYTHON_LIBRARY_CONSTANT)

clean-autogrenerated:
	rm -f $(PYTHON_LIBRARY_CONSTANT)

clean: clean-autogrenerated
	rm -rf $(BUILD_DIR)
	rm -rf $(LIB_PREFIX)/libgaussField/build
	rm -f  $(EXEC_NAME).spec
	rm -f $(CODE_DIR)/build.txt

clean-app:
	rm -rf $(EXEC_NAME)

clean-all: clean clean-safety clean-tests clean-cache

clean-cache: clean-__pycache__ clean-pyc

clean-__pycache__:
	rm -rf $(shell find $(SOURCE_DIR) -name __pycache__)

clean-pyc:
	rm -f $(shell find $(SOURCE_DIR) -name *.pyc)

docker-image: check-docker-dependencies
	docker build --rm --tag $(IMAGE_NAME) --file $(DOCKERFILE) .

docker-login:
	docker login $(DOCKER_REGISTRY_SERVER)
	# TODO: Add new user / bot to gitlab

docker-push-image:
	docker build --tag $(DOCKER_REGISTRY)/$(IMAGE_NAME) --file $(DOCKERFILE) .
	docker push $(DOCKER_REGISTRY)/$(IMAGE_NAME)

check-docker-dependencies:
	[[ -d gcc-$(GCC_VERSION) ]] || { cp -R /prog/sdpsoft/gcc-$(GCC_VERSION) .; }

copy-source:
	tar --exclude='$(CODE_DIR)/.git/' --exclude="$(CODE_DIR)/documentation" -cvzf code.tar.gz *

check-requirements:
	piprot --outdated $(CODE_DIR)/requirements.txt

safety-check: clean-safety get-vulnerability-db
	safety check --full-report --db $(VULNERABILITY_DB)

get-vulnerability-db:
	mkdir -p $(VULNERABILITY_DB) && \
    for file in 'insecure.json' 'insecure_full.json' ; do \
        curl --proxy $(HTTP_PROXY) \
             --output $(VULNERABILITY_DB)/$$file \
             --insecure \
             https://raw.githubusercontent.com/pyupio/safety-db/master/data/$$file; \
    done

clean-safety:
	rm -rf $(VULNERABILITY_DB)

unit-tests: copy-libdraw-to-test run-tests clean-tests

copy-libdraw-to-test: libdraw2D.so

run-tests:
	cd $(TEST_FOLDER) && \
	pytest --basetemp=$(TEST_FOLDER)

clean-tests:
	rm -rf $(TEST_FOLDER)/.cache && \
	rm -f  $(TEST_FOLDER)/*.dat  && \
	rm -f  $(TEST_FOLDER)/*.xml && \
	rm -f  $(TEST_FOLDER)/libdraw2D.so

# TODO: Add diagrams for Previewer, and other files / classes of interest
uml-diagrams:
	cd $(CODE_DIR) && \
	pyreverse -ASmy -k -o png $(ENTRY_POINT) -p APS-GUI

linting:
	pylint $(SOURCE_DIR)

print-%  : ; @echo $($*)
