[tools]
node = { version = "22.23.2", postinstall = '''
cd "${MISE_CONFIG_ROOT}/gui"
corepack enable
corepack install
''' }
python = "3.11.13"
pre-commit = "4.6.0"
uv = "0.8.22"
vite-plus = "0.3.0"
oxfmt = "0.65.0"

[plugins]
vite-plus = "https://github.com/markmals/mise-vite-plus"

[tasks."format:oxfmt"]
run = "oxfmt"

[tasks."lint:gui"]
dir = "gui"
run = "vp lint"

[tasks."dependencies:python"]
run = "uv sync --no-install-project"
sources = ["pyproject.toml", "uv.lock"]
outputs = [".venv/"]

[tasks."dependencies:docs"]
run = "uv sync --group=docs --no-install-project"
sources = ["pyproject.toml", "uv.lock"]
outputs = [".venv"]

[tasks."dependencies:node"]
run = """
corepack enable
corepack install
yarn install --frozen-lockfile
"""
dir = "gui"
sources = ["gui/package.json", "gui/yarn.lock"]
outputs = ["gui/node_modules/"]

[tasks.dependencies]
depends = ["dependencies:python", "dependencies:node"]

[tasks."serve:docs"]
run = "uv run --no-project mkdocs serve"
depends = ["dependencies:docs"]

[tasks.build-containers]
run = 'docker compose build --build-arg="RMS_IMAGE=$RMS_IMAGE" {{option(name="only", var=true)}}'
env = { _.file = ".env" }

[tasks."unit-test:python"]
depends = ["build-containers --only api"]
run = "docker compose run --rm api uv run pytest aps/tests"

[env]
_.python.venv = { path = ".venv", create = false }
