[tasks."dependencies:python"]
run = "uv sync --no-install-project"
sources = ["pyproject.toml", "uv.lock"]
outputs = [".venv/"]

[tasks."dependencies:docs"]
run = "uv sync --group=docs --no-install-project"
sources = ["pyproject.toml", "uv.lock"]
outputs = [".venv"]

[tasks."dependencies:node"]
run = """
corepack enable
corepack install
yarn install --frozen-lockfile
"""
dir = "gui"
sources = ["gui/package.json", "gui/yarn.lock"]
outputs = ["gui/node_modules/"]

[tasks.dependencies]
depends = ["dependencies:python", "dependencies:node"]

[tasks."serve:docs"]
run = "uv run --no-project mkdocs serve"
depends = ["dependencies:docs"]

[tasks.build-containers]
usage = '''
flag "--only <only>" help="Specify a single container to build"
'''
run = 'docker compose build --build-arg="RMS_IMAGE=$RMS_IMAGE" {{usage.only}}'
env = { _.file = ".env" }

[tasks."unit-test:python"]
depends = ["build-containers --only api"]
run = "docker compose run --rm api uv run pytest tests"

[env]
_.python.venv = { path = ".venv", create = false }
