# -*- coding: utf-8 -*-
from src.utils.constants.simple import Debug
from typing import Dict, List, Optional, Union
from xml.etree.ElementTree import Element, ElementTree


class APSMainFaciesTable:
    def __init__(
        self,
        ET_Tree: Optional[ElementTree] = None,
        modelFileName: Optional[str] = None,
        fTable: Optional[Dict[int, str]] = None,
        debug_level: Debug = Debug.OFF
    ) -> None: ...
    def __len__(self) -> int: ...
    def XMLAddElement(self, root: Element) -> None: ...
    def addFacies(self, faciesName: str, code: int) -> int: ...
    def getClassName(self) -> str: ...
    def getFaciesCode(self, fIndx: int) -> int: ...
    def getFaciesCodeForFaciesName(self, fName: str) -> int: ...
    def getFaciesIndx(self, fName: str) -> int: ...
    def getFaciesName(self, fIndx: int) -> str: ...
    def getFaciesTable(self) -> List[List[Union[str, int]]]: ...
    def has_facies_int_facies_table(self, fName: str) -> bool: ...
    def removeFacies(self, faciesName: str) -> None: ...
