from numpy import (
    float32,
    float64,
    ndarray,
)
from src.algorithms.APSMainFaciesTable import APSMainFaciesTable
from typing import (
    List,
    Optional,
    Tuple,
    Union,
)
from xml.etree.ElementTree import Element


class Trunc2D_Base:
    def _XMLAddElement(self, parent: Element) -> None: ...
    def __init__(
        self,
        trRuleXML: Optional[Element] = None,
        mainFaciesTable: Optional[APSMainFaciesTable] = None,
        faciesInZone: Optional[List[str]] = None,
        gaussFieldsInZone: Optional[List[str]] = None,
        debug_level: int = <Debug.OFF: 0>,
        modelFileName: Optional[str] = None,
        nGaussFieldsInBackGroundModel: int = 2
    ) -> None: ...
    def _addFaciesToTruncRule(self, fName: str) -> Tuple[int, int, int, int]: ...
    def _checkFaciesForZone(self) -> None: ...
    def _interpretXMLTree_overlay_facies(
        self,
        trRuleXML: Element,
        modelFileName: str,
        zoneNumber: Optional[int]
    ) -> None: ...
    def _isFaciesProbEqualOne(self, faciesProb: List[float]) -> bool: ...
    @staticmethod
    def _isInsidePolygon(
        polygon: List[List[float]],
        xInput: Union[float32, float64],
        yInput: Union[float32, float64]
    ) -> bool: ...
    @staticmethod
    def _makeKey(faciesProb: List[float], keyResolution: int) -> Tuple[float, ...]: ...
    @staticmethod
    def _makeRoundOfFaciesProb(faciesProb: List[float], keyResolution: int) -> List[float]: ...
    def _modifyBackgroundFaciesArea(self, faciesProb: List[float]) -> ndarray: ...
    def _setEmpty(self) -> None: ...
    def _setGaussFieldForBackgroundFaciesTruncationMap(
        self,
        gaussFieldsInZone: List[str],
        alphaFieldNameForBackGroundFacies: List[str],
        nGaussFieldsInBackGroundModel: int
    ) -> None: ...
    def _setModelledFacies(
        self,
        mainFaciesTable: APSMainFaciesTable,
        faciesInZone: List[str]
    ) -> None: ...
    def _setOverlayFaciesDataStructure(
        self,
        overlayGroups: List[List[Union[List[List[Union[str, float]]], List[str]]]]
    ) -> None: ...
    def _truncateOverlayFacies(self, indx: int, alphaCoord: ndarray) -> Tuple[int, int]: ...
    def getAlphaIndexInZone(self, alphaName: str) -> int: ...
    def getBackgroundFaciesInTruncRuleIndex(self, fName: str) -> int: ...
    def getEpsFaciesProb(self) -> float: ...
    def getFaciesInTruncRule(self) -> List[str]: ...
    def getFaciesInTruncRuleIndex(self, fName: str) -> int: ...
    def getFaciesInZoneIndex(self, fName: str) -> int: ...
    def getNGaussFieldsInModel(self) -> int: ...
