# -*- coding: utf-8 -*-
from numpy import ndarray

from src.algorithms.Trunc2D_Base_xml import Trunc2D_Base
from src.algorithms.APSMainFaciesTable import APSMainFaciesTable
from src.utils.constants.simple import Debug
from typing import List, Optional, Tuple, Union
from xml.etree.ElementTree import Element


class Trunc3D_bayfill(Trunc2D_Base):
    def __init__(
        self,
        trRuleXML: Optional[Element] = None,
        mainFaciesTable: Optional[APSMainFaciesTable] = None,
        faciesInZone: Optional[List[str]] = None,
        gaussFieldsInZone: Optional[List[str]] = None,
        debug_level: int = Debug.OFF,
        modelFileName: Optional[str] = None
    ) -> None: ...
    def __interpretXMLTree(self, trRuleXML, modelFileName): ...
    def XMLAddElement(self, parent: Element, zone_number:str, region_number:str, fmu_attributes:List[str]) -> None: ...
    def defineFaciesByTruncRule(self, alphaCoord: Union[ndarray, List[float]]) -> Tuple[int, int]: ...
    def getClassName(self) -> str: ...
    def getFaciesInTruncRule(self) -> List[str]: ...
    def getNGaussFieldsInModel(self) -> int: ...
    def initialize(
        self,
        mainFaciesTable: APSMainFaciesTable,
        faciesInZone: List[str],
        faciesInTruncRule: List[str],
        gaussFieldsInZone: List[str],
        alphaFieldNameForBackGroundFacies: List[str],
        sf_value: float,
        sf_name: Optional[str],
        ysf: float,
        sbhd: float,
        useConstTruncParam: int,
        debug_level: Debug = Debug.OFF
    ) -> None: ...
    def getTruncationParam(self, gridModel, realNumber): ...
    def faciesIndxPerPolygon(self): ...
    def setTruncRule(self, faciesProb: Union[ndarray, List[float]], cellIndx: int = 0) -> None: ...
    def useConstTruncModelParam(self) -> bool: ...
    def truncMapPolygons(
        self
    ) -> Union[List[Union[List[Union[List[float], List[Union[float, int]]]], List[List[float]]]], List[List[List[float]]]]: ...
    def setSFParam(self, sfValue: float) -> None: ...
    def setSFParamFmuUpdatable(self, value: bool) -> None: ...
    def setYSFParam(self, ysfValue: float) -> None: ...
    def setYSFParamFmuUpdatable(self, value: bool) -> None: ...
    def setSBHDParam(self, sbhdValue: float) -> None: ...
    def setSBHDParamFmuUpdatable(self, value: bool) -> None: ...
