import {defineConfig} from 'oxlint'

export default defineConfig({
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'vue'],
      jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    categories: {
      correctness: 'warn',
      // correctness: 'error',
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    env: {
      builtin: true,
      es2020: true,
    },
    ignorePatterns: ['**/dist/**', '**/dist-ssr/**', '**/coverage/**'],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'vue/no-arrow-functions-in-watch': 'error',
      'vue/no-async-in-computed-properties': 'error',
      'vue/no-computed-properties-in-data': 'error',
      'vue/no-deprecated-data-object-declaration': 'error',
      'vue/no-deprecated-delete-set': 'error',
      'vue/no-deprecated-destroyed-lifecycle': 'error',
      'vue/no-deprecated-events-api': 'error',
      'vue/no-deprecated-model-definition': 'error',
      'vue/no-deprecated-props-default-this': 'error',
      'vue/no-deprecated-vue-config-keycodes': 'error',
      'vue/no-dupe-keys': 'error',
      'vue/no-export-in-script-setup': 'error',
      'vue/no-expose-after-await': 'error',
      'vue/no-lifecycle-after-await': 'error',
      'vue/no-reserved-component-names': 'error',
      'vue/no-reserved-keys': 'error',
      'vue/no-reserved-props': 'error',
      'vue/no-shared-component-data': 'error',
      'vue/no-side-effects-in-computed-properties': 'error',
      'vue/no-watch-after-await': 'error',
      'vue/prefer-import-from-vue': 'error',
      'vue/require-prop-type-constructor': 'error',
      'vue/require-render-return': 'error',
      'vue/require-slots-as-functions': 'error',
      'vue/return-in-computed-property': 'error',
      'vue/return-in-emits-validator': 'error',
      'vue/valid-define-emits': 'error',
      'vue/valid-define-options': 'error',
      'vue/valid-define-props': 'error',
      'vue/valid-next-tick': 'error',
      'vue/component-definition-name-casing': 'warn',
      'vue/prop-name-casing': 'warn',
      'vue/require-default-prop': 'warn',
      'vue/require-prop-types': 'warn',
      'vue/no-multiple-slot-args': 'warn',
      'vue/no-required-prop-with-default': 'warn',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      // 'vuetify/no-deprecated-classes': 'error',
      // 'vuetify/no-deprecated-colors': 'error',
      // 'vuetify/no-deprecated-components': 'error',
      // 'vuetify/no-deprecated-events': 'error',
      // 'vuetify/no-deprecated-props': 'error',
      // 'vuetify/no-deprecated-slots': 'error',
      // 'vuetify/no-deprecated-imports': 'error',
      // 'vuetify/grid-unknown-attributes': 'error',
      // 'security/detect-buffer-noassert': 'warn',
      // 'security/detect-child-process': 'warn',
      // 'security/detect-disable-mustache-escape': 'warn',
      // 'security/detect-eval-with-expression': 'warn',
      // 'security/detect-new-buffer': 'warn',
      // 'security/detect-no-csrf-before-method-override': 'warn',
      // 'security/detect-non-literal-fs-filename': 'warn',
      // 'security/detect-non-literal-regexp': 'warn',
      // 'security/detect-non-literal-require': 'warn',
      // 'security/detect-possible-timing-attacks': 'warn',
      // 'security/detect-pseudoRandomBytes': 'warn',
      // 'security/detect-unsafe-regex': 'warn',
      // 'security/detect-bidi-characters': 'warn',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts', '**/*.vue'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['**/*.js', '**/*.jsx', '**/*.cjs', '**/*.mjs'],
        rules: {
          'typescript/await-thenable': 'off',
          'typescript/consistent-return': 'off',
          'typescript/consistent-type-exports': 'off',
          'typescript/dot-notation': 'off',
          'typescript/no-array-delete': 'off',
          'typescript/no-base-to-string': 'off',
          'typescript/no-confusing-void-expression': 'off',
          'typescript/no-deprecated': 'off',
          'typescript/no-duplicate-type-constituents': 'off',
          'typescript/no-floating-promises': 'off',
          'typescript/no-for-in-array': 'off',
          'typescript/no-implied-eval': 'off',
          'typescript/no-meaningless-void-operator': 'off',
          'typescript/no-misused-promises': 'off',
          'typescript/no-misused-spread': 'off',
          'typescript/no-mixed-enums': 'off',
          'typescript/no-redundant-type-constituents': 'off',
          'typescript/no-unnecessary-boolean-literal-compare': 'off',
          'typescript/no-unnecessary-condition': 'off',
          'typescript/no-unnecessary-qualifier': 'off',
          'typescript/no-unnecessary-template-expression': 'off',
          'typescript/no-unnecessary-type-arguments': 'off',
          'typescript/no-unnecessary-type-assertion': 'off',
          'typescript/no-unnecessary-type-conversion': 'off',
          'typescript/no-unnecessary-type-parameters': 'off',
          'typescript/no-unsafe-argument': 'off',
          'typescript/no-unsafe-assignment': 'off',
          'typescript/no-unsafe-call': 'off',
          'typescript/no-unsafe-enum-comparison': 'off',
          'typescript/no-unsafe-member-access': 'off',
          'typescript/no-unsafe-return': 'off',
          'typescript/no-unsafe-type-assertion': 'off',
          'typescript/no-unsafe-unary-minus': 'off',
          'typescript/no-useless-default-assignment': 'off',
          'typescript/non-nullable-type-assertion-style': 'off',
          'typescript/only-throw-error': 'off',
          'typescript/prefer-find': 'off',
          'typescript/prefer-includes': 'off',
          'typescript/prefer-nullish-coalescing': 'off',
          'typescript/prefer-optional-chain': 'off',
          'typescript/prefer-promise-reject-errors': 'off',
          'typescript/prefer-readonly': 'off',
          'typescript/prefer-readonly-parameter-types': 'off',
          'typescript/prefer-reduce-type-parameter': 'off',
          'typescript/prefer-regexp-exec': 'off',
          'typescript/prefer-return-this-type': 'off',
          'typescript/prefer-string-starts-ends-with': 'off',
          'typescript/promise-function-async': 'off',
          'typescript/related-getter-setter-pairs': 'off',
          'typescript/require-array-sort-compare': 'off',
          'typescript/require-await': 'off',
          'typescript/restrict-plus-operands': 'off',
          'typescript/restrict-template-expressions': 'off',
          'typescript/return-await': 'off',
          'typescript/strict-boolean-expressions': 'off',
          'typescript/strict-void-return': 'off',
          'typescript/switch-exhaustiveness-check': 'off',
          'typescript/unbound-method': 'off',
          'typescript/use-unknown-in-catch-callback-variable': 'off',
        },
      },
      {
        files: ['src/components/baseComponents/headings/SectionTitle.vue'],
        rules: {
          'typescript/await-thenable': 'off',
          'typescript/consistent-return': 'off',
          'typescript/consistent-type-exports': 'off',
          'typescript/dot-notation': 'off',
          'typescript/no-array-delete': 'off',
          'typescript/no-base-to-string': 'off',
          'typescript/no-confusing-void-expression': 'off',
          'typescript/no-deprecated': 'off',
          'typescript/no-duplicate-type-constituents': 'off',
          'typescript/no-floating-promises': 'off',
          'typescript/no-for-in-array': 'off',
          'typescript/no-implied-eval': 'off',
          'typescript/no-meaningless-void-operator': 'off',
          'typescript/no-misused-promises': 'off',
          'typescript/no-misused-spread': 'off',
          'typescript/no-mixed-enums': 'off',
          'typescript/no-redundant-type-constituents': 'off',
          'typescript/no-unnecessary-boolean-literal-compare': 'off',
          'typescript/no-unnecessary-condition': 'off',
          'typescript/no-unnecessary-qualifier': 'off',
          'typescript/no-unnecessary-template-expression': 'off',
          'typescript/no-unnecessary-type-arguments': 'off',
          'typescript/no-unnecessary-type-assertion': 'off',
          'typescript/no-unnecessary-type-conversion': 'off',
          'typescript/no-unnecessary-type-parameters': 'off',
          'typescript/no-unsafe-argument': 'off',
          'typescript/no-unsafe-assignment': 'off',
          'typescript/no-unsafe-call': 'off',
          'typescript/no-unsafe-enum-comparison': 'off',
          'typescript/no-unsafe-member-access': 'off',
          'typescript/no-unsafe-return': 'off',
          'typescript/no-unsafe-type-assertion': 'off',
          'typescript/no-unsafe-unary-minus': 'off',
          'typescript/no-useless-default-assignment': 'off',
          'typescript/non-nullable-type-assertion-style': 'off',
          'typescript/only-throw-error': 'off',
          'typescript/prefer-find': 'off',
          'typescript/prefer-includes': 'off',
          'typescript/prefer-nullish-coalescing': 'off',
          'typescript/prefer-optional-chain': 'off',
          'typescript/prefer-promise-reject-errors': 'off',
          'typescript/prefer-readonly': 'off',
          'typescript/prefer-readonly-parameter-types': 'off',
          'typescript/prefer-reduce-type-parameter': 'off',
          'typescript/prefer-regexp-exec': 'off',
          'typescript/prefer-return-this-type': 'off',
          'typescript/prefer-string-starts-ends-with': 'off',
          'typescript/promise-function-async': 'off',
          'typescript/related-getter-setter-pairs': 'off',
          'typescript/require-array-sort-compare': 'off',
          'typescript/require-await': 'off',
          'typescript/restrict-plus-operands': 'off',
          'typescript/restrict-template-expressions': 'off',
          'typescript/return-await': 'off',
          'typescript/strict-boolean-expressions': 'off',
          'typescript/strict-void-return': 'off',
          'typescript/switch-exhaustiveness-check': 'off',
          'typescript/unbound-method': 'off',
          'typescript/use-unknown-in-catch-callback-variable': 'off',
          'typescript/consistent-type-imports': 'off',
        },
      },
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.vue'],
        rules: {
          'typescript/no-unsafe-argument': 'off',
          'typescript/no-unsafe-assignment': 'off',
          'typescript/no-unsafe-return': 'off',
          'typescript/no-unsafe-call': 'off',
          'typescript/no-unsafe-member-access': 'off',
        },
      },
      {
        files: ['**/*.js'],
        rules: {
          'no-use-before-define': [
            'error',
            {
              functions: false,
              classes: false,
              variables: false,
            },
          ],
          'typescript/no-var-requires': 'off',
        },
      },
      {
        files: ['**/*.cjs'],
        rules: {
          'typescript/no-require-imports': 'off',
        },
      },
    ],
  })
