# -*-python-*-
#
 
import os
import os.path

# 
# Set umask and file rights so that things are built and installed readable by others
#

umask = os.umask(002)
os.system('chmod o+r *.h')
os.system('chmod ug+rw *.h')

#
# Create variables instdir, bindir, libdir, and incdir, and alias install:
#

basedir = os.environ['SDP_BINDIST_ROOT'] # directory for "binary" distribution
instdir = os.environ['SDP_BINDIST']      # install directory 
 
bindir = instdir + '/bin'
libdir = instdir + '/lib'
incdir = instdir + '/inc'
incinstalldir = incdir + '/gaussfield'

Alias('install',[libdir,incinstalldir])

# -----------------------------------------------

# Actual scons commands start here:

opt = Environment(CXXFLAGS = '-O0 -g' , CPPPATH = ['.' , '..' , incdir] , LIBPATH = ['.',libdir])
#opt = Environment(CXXFLAGS = '-O3' , CPPPATH = ['.' , '..' , incdir] , LIBPATH = ['.',libdir])


lib_gauss = opt.Library('simGauss',['utl_malloc.c', 'lib_ran.c', 'lib_message.c' , 'lib_matr.c', 'simGauss2D.C', 'randomFuncs.C', 'linearsolver.C', 'vario2D.C', 'message.C', 'vario.C', 'gauss_table.C', 'statistics.C', 'SimUniformField2D.C','draw2DGaussField.C'])

Install(libdir,lib_gauss)
Install(incinstalldir,['gaussfield.h','definitions.h','lib_matr.h','message.h','statistics.h','gauss_table.h','lib_message.h','randomFuncs.h','utl.h','Grid1D_template.h','lib_ran.h','simGauss2D.h','vario2D.h','Grid2D_template.h','linearsolver.h','SimUniformField2D.h','vario.h','draw2DGaussField.h'])

