# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/APS_prototype.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ZoneParameterName(object):
    def setupUi(self, ZoneParameterName):
        ZoneParameterName.setObjectName("ZoneParameterName")
        ZoneParameterName.resize(1325, 911)
        ZoneParameterName.setMinimumSize(QtCore.QSize(0, 911))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        ZoneParameterName.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ZoneParameterName)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TruncationLibrary_GRF_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TruncationLibrary_GRF_tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TruncationLibrary_GRF_tabWidget.sizePolicy().hasHeightForWidth())
        self.TruncationLibrary_GRF_tabWidget.setSizePolicy(sizePolicy)
        self.TruncationLibrary_GRF_tabWidget.setMinimumSize(QtCore.QSize(600, 750))
        self.TruncationLibrary_GRF_tabWidget.setObjectName("TruncationLibrary_GRF_tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(80, 20, 491, 771))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.TruncationLibrary_gridLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.TruncationLibrary_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.TruncationLibrary_gridLayout.setObjectName("TruncationLibrary_gridLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_cubic = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_cubic.setFont(font)
        self.label_cubic.setObjectName("label_cubic")
        self.gridLayout_9.addWidget(self.label_cubic, 0, 0, 1, 1)
        self.m_button_type_a = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_a.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_a.setIcon(icon)
        self.m_button_type_a.setObjectName("m_button_type_a")
        self.gridLayout_9.addWidget(self.m_button_type_a, 2, 0, 1, 1)
        self.m_button_type_b = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_b.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_b.setIcon(icon1)
        self.m_button_type_b.setObjectName("m_button_type_b")
        self.gridLayout_9.addWidget(self.m_button_type_b, 2, 1, 1, 1)
        self.m_button_type_c = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_c.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_c.setIcon(icon2)
        self.m_button_type_c.setObjectName("m_button_type_c")
        self.gridLayout_9.addWidget(self.m_button_type_c, 2, 2, 1, 1)
        self.m_button_type_d = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_d.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_d.setIcon(icon3)
        self.m_button_type_d.setObjectName("m_button_type_d")
        self.gridLayout_9.addWidget(self.m_button_type_d, 2, 3, 1, 1)
        self.m_button_type_e = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_e.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_e.setIcon(icon4)
        self.m_button_type_e.setObjectName("m_button_type_e")
        self.gridLayout_9.addWidget(self.m_button_type_e, 2, 4, 1, 1)
        self.m_button_type_f = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_f.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_f.setIcon(icon5)
        self.m_button_type_f.setObjectName("m_button_type_f")
        self.gridLayout_9.addWidget(self.m_button_type_f, 3, 0, 1, 1)
        self.m_button_type_g = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_g.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_g.setIcon(icon6)
        self.m_button_type_g.setObjectName("m_button_type_g")
        self.gridLayout_9.addWidget(self.m_button_type_g, 3, 1, 1, 1)
        self.m_button_type_h = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_h.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_h.setIcon(icon7)
        self.m_button_type_h.setObjectName("m_button_type_h")
        self.gridLayout_9.addWidget(self.m_button_type_h, 3, 2, 1, 1)
        self.m_button_type_i = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_i.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_i.setIcon(icon8)
        self.m_button_type_i.setObjectName("m_button_type_i")
        self.gridLayout_9.addWidget(self.m_button_type_i, 3, 3, 1, 1)
        self.m_button_type_j = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_j.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeJ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_j.setIcon(icon9)
        self.m_button_type_j.setObjectName("m_button_type_j")
        self.gridLayout_9.addWidget(self.m_button_type_j, 3, 4, 1, 1)
        self.m_button_type_k = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_k.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_k.setIcon(icon10)
        self.m_button_type_k.setObjectName("m_button_type_k")
        self.gridLayout_9.addWidget(self.m_button_type_k, 4, 0, 1, 1)
        self.m_button_type_l = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_l.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_l.setIcon(icon11)
        self.m_button_type_l.setObjectName("m_button_type_l")
        self.gridLayout_9.addWidget(self.m_button_type_l, 4, 1, 1, 1)
        self.m_button_type_m = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_m.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_m.setIcon(icon12)
        self.m_button_type_m.setObjectName("m_button_type_m")
        self.gridLayout_9.addWidget(self.m_button_type_m, 4, 2, 1, 1)
        self.m_button_type_n = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_n.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_n.setIcon(icon13)
        self.m_button_type_n.setObjectName("m_button_type_n")
        self.gridLayout_9.addWidget(self.m_button_type_n, 4, 3, 1, 1)
        self.m_button_type_o = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_o.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_o.setIcon(icon14)
        self.m_button_type_o.setObjectName("m_button_type_o")
        self.gridLayout_9.addWidget(self.m_button_type_o, 4, 4, 1, 1)
        self.m_button_type_p = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_p.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_p.setIcon(icon15)
        self.m_button_type_p.setObjectName("m_button_type_p")
        self.gridLayout_9.addWidget(self.m_button_type_p, 5, 0, 1, 1)
        self.m_button_type_q = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_q.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeQ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_q.setIcon(icon16)
        self.m_button_type_q.setObjectName("m_button_type_q")
        self.gridLayout_9.addWidget(self.m_button_type_q, 5, 1, 1, 1)
        self.m_button_type_r = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_r.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_r.setIcon(icon17)
        self.m_button_type_r.setObjectName("m_button_type_r")
        self.gridLayout_9.addWidget(self.m_button_type_r, 5, 2, 1, 1)
        self.m_button_type_s = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_s.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_s.setIcon(icon18)
        self.m_button_type_s.setObjectName("m_button_type_s")
        self.gridLayout_9.addWidget(self.m_button_type_s, 5, 3, 1, 1)
        self.m_button_type_t = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_t.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_t.setIcon(icon19)
        self.m_button_type_t.setObjectName("m_button_type_t")
        self.gridLayout_9.addWidget(self.m_button_type_t, 5, 4, 1, 1)
        self.m_button_type_u = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_u.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_u.setIcon(icon20)
        self.m_button_type_u.setObjectName("m_button_type_u")
        self.gridLayout_9.addWidget(self.m_button_type_u, 6, 0, 1, 1)
        self.m_button_type_v = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_v.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_v.setIcon(icon21)
        self.m_button_type_v.setObjectName("m_button_type_v")
        self.gridLayout_9.addWidget(self.m_button_type_v, 6, 1, 1, 1)
        self.m_button_type_w = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_w.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_w.setIcon(icon22)
        self.m_button_type_w.setObjectName("m_button_type_w")
        self.gridLayout_9.addWidget(self.m_button_type_w, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 0, 2, 1, 1)
        self.TruncationLibrary_gridLayout.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_non_cubic = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_non_cubic.setFont(font)
        self.label_non_cubic.setObjectName("label_non_cubic")
        self.gridLayout_4.addWidget(self.label_non_cubic, 0, 0, 1, 2)
        self.m_button_type_I = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_I.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_I.setIcon(icon23)
        self.m_button_type_I.setObjectName("m_button_type_I")
        self.gridLayout_4.addWidget(self.m_button_type_I, 2, 0, 1, 1)
        self.m_button_type_II = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_II.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_II.setIcon(icon24)
        self.m_button_type_II.setObjectName("m_button_type_II")
        self.gridLayout_4.addWidget(self.m_button_type_II, 2, 1, 1, 1)
        self.m_button_type_III = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_III.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeIII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_III.setIcon(icon25)
        self.m_button_type_III.setObjectName("m_button_type_III")
        self.gridLayout_4.addWidget(self.m_button_type_III, 2, 2, 1, 1)
        self.m_button_type_IV = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_IV.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeIV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_IV.setIcon(icon26)
        self.m_button_type_IV.setObjectName("m_button_type_IV")
        self.gridLayout_4.addWidget(self.m_button_type_IV, 2, 3, 1, 1)
        self.m_button_type_V = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_V.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeVI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_V.setIcon(icon27)
        self.m_button_type_V.setObjectName("m_button_type_V")
        self.gridLayout_4.addWidget(self.m_button_type_V, 2, 4, 1, 1)
        self.m_button_type_VI = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_VI.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_VI.setIcon(icon28)
        self.m_button_type_VI.setObjectName("m_button_type_VI")
        self.gridLayout_4.addWidget(self.m_button_type_VI, 3, 0, 1, 1)
        self.m_button_type_VII = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_VII.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeVIII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_VII.setIcon(icon29)
        self.m_button_type_VII.setObjectName("m_button_type_VII")
        self.gridLayout_4.addWidget(self.m_button_type_VII, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        self.TruncationLibrary_gridLayout.addLayout(self.gridLayout_4, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.TruncationLibrary_gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_bayfill = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bayfill.setFont(font)
        self.label_bayfill.setObjectName("label_bayfill")
        self.gridLayout_5.addWidget(self.label_bayfill, 0, 0, 1, 1)
        self.m_button_type_VIII = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_type_VIII.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeVII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_VIII.setIcon(icon30)
        self.m_button_type_VIII.setObjectName("m_button_type_VIII")
        self.gridLayout_5.addWidget(self.m_button_type_VIII, 1, 0, 1, 1)
        self.TruncationLibrary_gridLayout.addLayout(self.gridLayout_5, 6, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.m_button_assign_probability = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_assign_probability.setObjectName("m_button_assign_probability")
        self.gridLayout_15.addWidget(self.m_button_assign_probability, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem3, 0, 1, 1, 1)
        self.m_toggle_condition_to_wells = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.m_toggle_condition_to_wells.setObjectName("m_toggle_condition_to_wells")
        self.gridLayout_15.addWidget(self.m_toggle_condition_to_wells, 0, 0, 1, 1)
        self.TruncationLibrary_gridLayout.addLayout(self.gridLayout_15, 8, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.m_button_previewer = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_previewer.setObjectName("m_button_previewer")
        self.gridLayout_14.addWidget(self.m_button_previewer, 0, 0, 1, 1)
        self.m_button_save = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_save.setObjectName("m_button_save")
        self.gridLayout_14.addWidget(self.m_button_save, 0, 1, 1, 1)
        self.m_button_save_as = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_save_as.setObjectName("m_button_save_as")
        self.gridLayout_14.addWidget(self.m_button_save_as, 0, 2, 1, 1)
        self.m_button_close = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_button_close.setObjectName("m_button_close")
        self.gridLayout_14.addWidget(self.m_button_close, 0, 3, 1, 1)
        self.TruncationLibrary_gridLayout.addLayout(self.gridLayout_14, 10, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.TruncationLibrary_gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.TruncationLibrary_gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.TruncationLibrary_gridLayout.addItem(spacerItem6, 9, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.TruncationLibrary_gridLayout.addItem(spacerItem7, 7, 0, 1, 1)
        self.label_truncation_library = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_truncation_library.setFont(font)
        self.label_truncation_library.setAlignment(QtCore.Qt.AlignCenter)
        self.label_truncation_library.setObjectName("label_truncation_library")
        self.TruncationLibrary_gridLayout.addWidget(self.label_truncation_library, 0, 0, 1, 1)
        self.TruncationLibrary_GRF_tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 0, 528, 821))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_gaussian_random_fields = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_gaussian_random_fields.setFont(font)
        self.label_gaussian_random_fields.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gaussian_random_fields.setObjectName("label_gaussian_random_fields")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_gaussian_random_fields)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_GRF1 = QtWidgets.QGridLayout()
        self.group_GRF1.setObjectName("group_GRF1")
        self.label_GRF1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF1.setFont(font)
        self.label_GRF1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF1.setObjectName("label_GRF1")
        self.group_GRF1.addWidget(self.label_GRF1, 0, 0, 1, 1)
        self.m_button_GRF1_settings = QtWidgets.QPushButton(self.layoutWidget)
        self.m_button_GRF1_settings.setObjectName("m_button_GRF1_settings")
        self.group_GRF1.addWidget(self.m_button_GRF1_settings, 0, 2, 1, 1)
        self.m_toggle_GRF1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.m_toggle_GRF1.setObjectName("m_toggle_GRF1")
        self.group_GRF1.addWidget(self.m_toggle_GRF1, 1, 2, 1, 1)
        self.m_plot_arear_GRF1 = QCustomPlot(self.layoutWidget)
        self.m_plot_arear_GRF1.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_arear_GRF1.setObjectName("m_plot_arear_GRF1")
        self.group_GRF1.addWidget(self.m_plot_arear_GRF1, 0, 1, 2, 1)
        self.verticalLayout.addLayout(self.group_GRF1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.group_GRF2 = QtWidgets.QGridLayout()
        self.group_GRF2.setObjectName("group_GRF2")
        self.label_GRF2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF2.setFont(font)
        self.label_GRF2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF2.setObjectName("label_GRF2")
        self.group_GRF2.addWidget(self.label_GRF2, 0, 0, 1, 1)
        self.m_button_GRF2_settings = QtWidgets.QPushButton(self.layoutWidget)
        self.m_button_GRF2_settings.setObjectName("m_button_GRF2_settings")
        self.group_GRF2.addWidget(self.m_button_GRF2_settings, 0, 2, 1, 1)
        self.m_toggle_GRF2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.m_toggle_GRF2.setObjectName("m_toggle_GRF2")
        self.group_GRF2.addWidget(self.m_toggle_GRF2, 1, 2, 1, 1)
        self.m_plot_arear_GRF2 = QCustomPlot(self.layoutWidget)
        self.m_plot_arear_GRF2.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_arear_GRF2.setObjectName("m_plot_arear_GRF2")
        self.group_GRF2.addWidget(self.m_plot_arear_GRF2, 0, 1, 2, 1)
        self.verticalLayout.addLayout(self.group_GRF2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.group_GRF3 = QtWidgets.QGridLayout()
        self.group_GRF3.setObjectName("group_GRF3")
        self.label_GRF3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF3.setFont(font)
        self.label_GRF3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF3.setObjectName("label_GRF3")
        self.group_GRF3.addWidget(self.label_GRF3, 0, 0, 1, 1)
        self.m_button_GRF3_settings = QtWidgets.QPushButton(self.layoutWidget)
        self.m_button_GRF3_settings.setObjectName("m_button_GRF3_settings")
        self.group_GRF3.addWidget(self.m_button_GRF3_settings, 0, 2, 1, 1)
        self.m_toggle_GRF3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.m_toggle_GRF3.setObjectName("m_toggle_GRF3")
        self.group_GRF3.addWidget(self.m_toggle_GRF3, 1, 2, 1, 1)
        self.m_plot_arear_GRF2_2 = QCustomPlot(self.layoutWidget)
        self.m_plot_arear_GRF2_2.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_arear_GRF2_2.setObjectName("m_plot_arear_GRF2_2")
        self.group_GRF3.addWidget(self.m_plot_arear_GRF2_2, 0, 1, 2, 1)
        self.verticalLayout.addLayout(self.group_GRF3)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.buttonBox_gaussian_fields = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox_gaussian_fields.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_gaussian_fields.setObjectName("buttonBox_gaussian_fields")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonBox_gaussian_fields)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        self.m_button_apply_GRFs = QtWidgets.QPushButton(self.layoutWidget)
        self.m_button_apply_GRFs.setObjectName("m_button_apply_GRFs")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.m_button_apply_GRFs)
        self.TruncationLibrary_GRF_tabWidget.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.TruncationLibrary_GRF_tabWidget, 1, 0, 1, 1)
        ZoneParameterName.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ZoneParameterName)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1325, 20))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        ZoneParameterName.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ZoneParameterName)
        self.statusbar.setObjectName("statusbar")
        ZoneParameterName.setStatusBar(self.statusbar)
        self.dock_project_parameters = QtWidgets.QDockWidget(ZoneParameterName)
        self.dock_project_parameters.setMinimumSize(QtCore.QSize(685, 350))
        self.dock_project_parameters.setObjectName("dock_project_parameters")
        self.content_project_parameters = QtWidgets.QWidget()
        self.content_project_parameters.setObjectName("content_project_parameters")
        self.widget_project_parameter = QtWidgets.QTabWidget(self.content_project_parameters)
        self.widget_project_parameter.setGeometry(QtCore.QRect(10, 0, 641, 300))
        self.widget_project_parameter.setMinimumSize(QtCore.QSize(611, 300))
        self.widget_project_parameter.setObjectName("widget_project_parameter")
        self.tab_project = QtWidgets.QWidget()
        self.tab_project.setObjectName("tab_project")
        self.project = QtWidgets.QGroupBox(self.tab_project)
        self.project.setGeometry(QtCore.QRect(0, 20, 621, 250))
        self.project.setMinimumSize(QtCore.QSize(0, 250))
        self.project.setObjectName("project")
        self.formLayout_11 = QtWidgets.QFormLayout(self.project)
        self.formLayout_11.setObjectName("formLayout_11")
        self.layout_mode = QtWidgets.QFormLayout()
        self.layout_mode.setObjectName("layout_mode")
        self.m_rb_experimental_mode = QtWidgets.QRadioButton(self.project)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_experimental_mode.setFont(font)
        self.m_rb_experimental_mode.setObjectName("m_rb_experimental_mode")
        self.layout_mode.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.m_rb_experimental_mode)
        self.m_rb_read_rms_project_file = QtWidgets.QRadioButton(self.project)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_read_rms_project_file.setFont(font)
        self.m_rb_read_rms_project_file.setObjectName("m_rb_read_rms_project_file")
        self.layout_mode.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.m_rb_read_rms_project_file)
        self.formLayout_11.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.layout_mode)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_11.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem11)
        self.layout_load_rms_project = QtWidgets.QGridLayout()
        self.layout_load_rms_project.setObjectName("layout_load_rms_project")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_load_rms_project.addItem(spacerItem12, 1, 1, 1, 1)
        self.m_button_browse_project_file = QtWidgets.QPushButton(self.project)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.m_button_browse_project_file.setFont(font)
        self.m_button_browse_project_file.setObjectName("m_button_browse_project_file")
        self.layout_load_rms_project.addWidget(self.m_button_browse_project_file, 1, 5, 1, 1)
        self.m_edit_browse_project = QtWidgets.QLineEdit(self.project)
        self.m_edit_browse_project.setObjectName("m_edit_browse_project")
        self.layout_load_rms_project.addWidget(self.m_edit_browse_project, 1, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_load_rms_project.addItem(spacerItem13, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_load_rms_project.addItem(spacerItem14, 1, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_load_rms_project.addItem(spacerItem15, 1, 4, 1, 1)
        self.LocationRMSproject_FileLabel_2 = QtWidgets.QLabel(self.project)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LocationRMSproject_FileLabel_2.setFont(font)
        self.LocationRMSproject_FileLabel_2.setObjectName("LocationRMSproject_FileLabel_2")
        self.layout_load_rms_project.addWidget(self.LocationRMSproject_FileLabel_2, 1, 0, 1, 1)
        self.formLayout_11.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.layout_load_rms_project)
        self.button_box_Ok_Cancel_project = QtWidgets.QDialogButtonBox(self.project)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_box_Ok_Cancel_project.setFont(font)
        self.button_box_Ok_Cancel_project.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box_Ok_Cancel_project.setObjectName("button_box_Ok_Cancel_project")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.button_box_Ok_Cancel_project)
        self.widget_project_parameter.addTab(self.tab_project, "")
        self.tab_parameters = QtWidgets.QWidget()
        self.tab_parameters.setObjectName("tab_parameters")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_parameters)
        self.layoutWidget_6.setGeometry(QtCore.QRect(80, 20, 451, 151))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.layout_parameters = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.layout_parameters.setContentsMargins(0, 0, 0, 0)
        self.layout_parameters.setObjectName("layout_parameters")
        self.label_workflow_name = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_workflow_name.setFont(font)
        self.label_workflow_name.setObjectName("label_workflow_name")
        self.layout_parameters.addWidget(self.label_workflow_name, 0, 0, 1, 1)
        self.m_edit_workflow_name = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.m_edit_workflow_name.setObjectName("m_edit_workflow_name")
        self.layout_parameters.addWidget(self.m_edit_workflow_name, 0, 2, 1, 1)
        self.label_grid_model_name = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_grid_model_name.setFont(font)
        self.label_grid_model_name.setObjectName("label_grid_model_name")
        self.layout_parameters.addWidget(self.label_grid_model_name, 1, 0, 1, 1)
        self.m_edit_grid_model_name = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.m_edit_grid_model_name.setObjectName("m_edit_grid_model_name")
        self.layout_parameters.addWidget(self.m_edit_grid_model_name, 1, 2, 1, 1)
        self.label_facies_parameter_name = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_facies_parameter_name.setFont(font)
        self.label_facies_parameter_name.setObjectName("label_facies_parameter_name")
        self.layout_parameters.addWidget(self.label_facies_parameter_name, 2, 0, 1, 1)
        self.m_edit_facies_parameter_name = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.m_edit_facies_parameter_name.setObjectName("m_edit_facies_parameter_name")
        self.layout_parameters.addWidget(self.m_edit_facies_parameter_name, 2, 2, 1, 1)
        self.label_zones_parameter_name = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_zones_parameter_name.setFont(font)
        self.label_zones_parameter_name.setObjectName("label_zones_parameter_name")
        self.layout_parameters.addWidget(self.label_zones_parameter_name, 3, 0, 1, 1)
        self.m_edit_zones_parameter_name = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.m_edit_zones_parameter_name.setObjectName("m_edit_zones_parameter_name")
        self.layout_parameters.addWidget(self.m_edit_zones_parameter_name, 3, 2, 1, 1)
        self.label_gaussian_parameter_name = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_gaussian_parameter_name.setFont(font)
        self.label_gaussian_parameter_name.setObjectName("label_gaussian_parameter_name")
        self.layout_parameters.addWidget(self.label_gaussian_parameter_name, 4, 0, 1, 1)
        self.m_edit_gaussian_parameter_name = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.m_edit_gaussian_parameter_name.setObjectName("m_edit_gaussian_parameter_name")
        self.layout_parameters.addWidget(self.m_edit_gaussian_parameter_name, 4, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem16, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem17, 1, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem18, 2, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem19, 3, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem20, 4, 1, 1, 1)
        self.widget_project_parameter.addTab(self.tab_parameters, "")
        self.dock_project_parameters.setWidget(self.content_project_parameters)
        ZoneParameterName.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_project_parameters)
        self.dock_selection_zones_Facies = QtWidgets.QDockWidget(ZoneParameterName)
        self.dock_selection_zones_Facies.setMinimumSize(QtCore.QSize(611, 221))
        self.dock_selection_zones_Facies.setObjectName("dock_selection_zones_Facies")
        self.content_selection_zones_Facies = QtWidgets.QWidget()
        self.content_selection_zones_Facies.setObjectName("content_selection_zones_Facies")
        self.layoutWidget_7 = QtWidgets.QWidget(self.content_selection_zones_Facies)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 20, 457, 141))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.layout_selection = QtWidgets.QFormLayout(self.layoutWidget_7)
        self.layout_selection.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.layout_selection.setContentsMargins(0, 0, 0, 0)
        self.layout_selection.setObjectName("layout_selection")
        self.label_selection = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_selection.setFont(font)
        self.label_selection.setObjectName("label_selection")
        self.layout_selection.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_selection)
        self.layout_select_modelled_zones = QtWidgets.QHBoxLayout()
        self.layout_select_modelled_zones.setObjectName("layout_select_modelled_zones")
        self.label_Select_modelled_zones = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_Select_modelled_zones.setFont(font)
        self.label_Select_modelled_zones.setObjectName("label_Select_modelled_zones")
        self.layout_select_modelled_zones.addWidget(self.label_Select_modelled_zones)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_select_modelled_zones.addItem(spacerItem21)
        self.m_rb_zones_selection = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_zones_selection.setFont(font)
        self.m_rb_zones_selection.setObjectName("m_rb_zones_selection")
        self.layout_select_modelled_zones.addWidget(self.m_rb_zones_selection)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_select_modelled_zones.addItem(spacerItem22)
        self.m_rb_select_all = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_select_all.setFont(font)
        self.m_rb_select_all.setObjectName("m_rb_select_all")
        self.layout_select_modelled_zones.addWidget(self.m_rb_select_all)
        self.layout_selection.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.layout_select_modelled_zones)
        spacerItem23 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_selection.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem23)
        self.layout_select_modelled_facies = QtWidgets.QHBoxLayout()
        self.layout_select_modelled_facies.setObjectName("layout_select_modelled_facies")
        self.label_select_modelled_facies = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_select_modelled_facies.setFont(font)
        self.label_select_modelled_facies.setObjectName("label_select_modelled_facies")
        self.layout_select_modelled_facies.addWidget(self.label_select_modelled_facies)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_select_modelled_facies.addItem(spacerItem24)
        self.m_rb_selection_facies = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_selection_facies.setFont(font)
        self.m_rb_selection_facies.setObjectName("m_rb_selection_facies")
        self.layout_select_modelled_facies.addWidget(self.m_rb_selection_facies)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_select_modelled_facies.addItem(spacerItem25)
        self.m_rb_select_all_facies = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_select_all_facies.setFont(font)
        self.m_rb_select_all_facies.setObjectName("m_rb_select_all_facies")
        self.layout_select_modelled_facies.addWidget(self.m_rb_select_all_facies)
        self.layout_selection.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.layout_select_modelled_facies)
        self.button_box_selection_ok_cancel = QtWidgets.QDialogButtonBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.button_box_selection_ok_cancel.setFont(font)
        self.button_box_selection_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box_selection_ok_cancel.setObjectName("button_box_selection_ok_cancel")
        self.layout_selection.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.button_box_selection_ok_cancel)
        spacerItem26 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_selection.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem26)
        self.dock_selection_zones_Facies.setWidget(self.content_selection_zones_Facies)
        ZoneParameterName.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_selection_zones_Facies)
        self.actionNew = QtWidgets.QAction(ZoneParameterName)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(ZoneParameterName)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(ZoneParameterName)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(ZoneParameterName)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClos = QtWidgets.QAction(ZoneParameterName)
        self.actionClos.setObjectName("actionClos")
        self.actionQuit = QtWidgets.QAction(ZoneParameterName)
        self.actionQuit.setObjectName("actionQuit")
        self.dock_project_parameters.raise_()
        self.dock_selection_zones_Facies.raise_()
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addAction(self.actionClos)
        self.menu_File.addAction(self.actionQuit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(ZoneParameterName)
        self.TruncationLibrary_GRF_tabWidget.setCurrentIndex(0)
        self.widget_project_parameter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ZoneParameterName)

    def retranslateUi(self, ZoneParameterName):
        _translate = QtCore.QCoreApplication.translate
        ZoneParameterName.setWindowTitle(_translate("ZoneParameterName", "MainWindow"))
        self.label_cubic.setText(_translate("ZoneParameterName", "Cubic"))
        self.label_non_cubic.setText(_translate("ZoneParameterName", "Non-Cubic"))
        self.label_bayfill.setText(_translate("ZoneParameterName", "Bayfill "))
        self.m_button_assign_probability.setText(_translate("ZoneParameterName", "Assign Probability"))
        self.m_toggle_condition_to_wells.setText(_translate("ZoneParameterName", "Condition to wells"))
        self.m_button_previewer.setText(_translate("ZoneParameterName", "&Previewer"))
        self.m_button_save.setText(_translate("ZoneParameterName", "&Save"))
        self.m_button_save_as.setText(_translate("ZoneParameterName", "&Save As.."))
        self.m_button_close.setText(_translate("ZoneParameterName", "&Close"))
        self.label_truncation_library.setText(_translate("ZoneParameterName", "Truncation Rule Library"))
        self.TruncationLibrary_GRF_tabWidget.setTabText(self.TruncationLibrary_GRF_tabWidget.indexOf(self.tab_3), _translate("ZoneParameterName", "Truncation Rule"))
        self.label_gaussian_random_fields.setText(_translate("ZoneParameterName", "Gaussian Random  Fields"))
        self.label_GRF1.setText(_translate("ZoneParameterName", "GRF1"))
        self.m_button_GRF1_settings.setText(_translate("ZoneParameterName", "GRF1 Settings"))
        self.m_toggle_GRF1.setText(_translate("ZoneParameterName", "GRF1 Applied"))
        self.label_GRF2.setText(_translate("ZoneParameterName", "GRF2"))
        self.m_button_GRF2_settings.setText(_translate("ZoneParameterName", "GRF2 Settings"))
        self.m_toggle_GRF2.setText(_translate("ZoneParameterName", "GRF2 Applied"))
        self.label_GRF3.setText(_translate("ZoneParameterName", "GRF3"))
        self.m_button_GRF3_settings.setText(_translate("ZoneParameterName", "GRF3 Settings"))
        self.m_toggle_GRF3.setText(_translate("ZoneParameterName", "GRF3 Applied"))
        self.m_button_apply_GRFs.setText(_translate("ZoneParameterName", "&Apply GRF\'s"))
        self.TruncationLibrary_GRF_tabWidget.setTabText(self.TruncationLibrary_GRF_tabWidget.indexOf(self.tab_4), _translate("ZoneParameterName", "GRF"))
        self.menu_File.setTitle(_translate("ZoneParameterName", "&File"))
        self.menu_Edit.setTitle(_translate("ZoneParameterName", "&Edit"))
        self.menu_View.setTitle(_translate("ZoneParameterName", "&View"))
        self.menu_Help.setTitle(_translate("ZoneParameterName", "&Help"))
        self.m_rb_experimental_mode.setText(_translate("ZoneParameterName", "Experimental mode"))
        self.m_rb_read_rms_project_file.setText(_translate("ZoneParameterName", "Read RMS project file"))
        self.m_button_browse_project_file.setText(_translate("ZoneParameterName", "Browse.."))
        self.LocationRMSproject_FileLabel_2.setText(_translate("ZoneParameterName", "Location RMS project file"))
        self.widget_project_parameter.setTabText(self.widget_project_parameter.indexOf(self.tab_project), _translate("ZoneParameterName", "Project"))
        self.label_workflow_name.setText(_translate("ZoneParameterName", "Workflow name"))
        self.label_grid_model_name.setText(_translate("ZoneParameterName", "Grid Model name"))
        self.label_facies_parameter_name.setText(_translate("ZoneParameterName", "Facies parameter name"))
        self.label_zones_parameter_name.setText(_translate("ZoneParameterName", "Zones parameter name"))
        self.label_gaussian_parameter_name.setText(_translate("ZoneParameterName", "Gaussian parameter name"))
        self.widget_project_parameter.setTabText(self.widget_project_parameter.indexOf(self.tab_parameters), _translate("ZoneParameterName", "Parameters"))
        self.label_selection.setText(_translate("ZoneParameterName", "Selection "))
        self.label_Select_modelled_zones.setText(_translate("ZoneParameterName", "Select modelled Zones"))
        self.m_rb_zones_selection.setText(_translate("ZoneParameterName", "Selection"))
        self.m_rb_select_all.setText(_translate("ZoneParameterName", "Select All.."))
        self.label_select_modelled_facies.setText(_translate("ZoneParameterName", "Select modelled Facies"))
        self.m_rb_selection_facies.setText(_translate("ZoneParameterName", "Selection"))
        self.m_rb_select_all_facies.setText(_translate("ZoneParameterName", "Select All.."))
        self.actionNew.setText(_translate("ZoneParameterName", "New"))
        self.actionOpen.setText(_translate("ZoneParameterName", "Open"))
        self.actionSave.setText(_translate("ZoneParameterName", "Save"))
        self.actionSave_As.setText(_translate("ZoneParameterName", "Save As.."))
        self.actionClos.setText(_translate("ZoneParameterName", "Close"))
        self.actionQuit.setText(_translate("ZoneParameterName", "Quit"))

from qcustomplot import QCustomPlot
from src.resources import Resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ZoneParameterName = QtWidgets.QMainWindow()
    ui = Ui_ZoneParameterName()
    ui.setupUi(ZoneParameterName)
    ZoneParameterName.show()
    sys.exit(app.exec_())

