# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/Assign_Probs.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_assign_probabilities(object):
    def setupUi(self, assign_probabilities):
        assign_probabilities.setObjectName("assign_probabilities")
        assign_probabilities.resize(454, 289)
        self.layoutWidget = QtWidgets.QWidget(assign_probabilities)
        self.layoutWidget.setGeometry(QtCore.QRect(28, 21, 401, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.Heading_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Heading_label.setFont(font)
        self.Heading_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Heading_label.setAutoFillBackground(False)
        self.Heading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Heading_label.setWordWrap(True)
        self.Heading_label.setObjectName("Heading_label")
        self.layout.addWidget(self.Heading_label, 0, 0, 1, 1)
        self.button_box_ok_cancle = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.button_box_ok_cancle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box_ok_cancle.setObjectName("button_box_ok_cancle")
        self.layout.addWidget(self.button_box_ok_cancle, 3, 0, 1, 1)
        self.layout_assignment = QtWidgets.QGridLayout()
        self.layout_assignment.setObjectName("layout_assignment")
        self.label_F1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_F1.setObjectName("label_F1")
        self.layout_assignment.addWidget(self.label_F1, 1, 0, 1, 1)
        self.m_edit_F1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_edit_F1.setObjectName("m_edit_F1")
        self.layout_assignment.addWidget(self.m_edit_F1, 1, 1, 1, 1)
        self.m_combobox_F1 = QtWidgets.QComboBox(self.layoutWidget)
        self.m_combobox_F1.setObjectName("m_combobox_F1")
        self.layout_assignment.addWidget(self.m_combobox_F1, 1, 2, 1, 1)
        self.label_F2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_F2.setObjectName("label_F2")
        self.layout_assignment.addWidget(self.label_F2, 2, 0, 1, 1)
        self.m_edit_F2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_edit_F2.setObjectName("m_edit_F2")
        self.layout_assignment.addWidget(self.m_edit_F2, 2, 1, 1, 1)
        self.m_combobox_F2 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_combobox_F2.sizePolicy().hasHeightForWidth())
        self.m_combobox_F2.setSizePolicy(sizePolicy)
        self.m_combobox_F2.setObjectName("m_combobox_F2")
        self.layout_assignment.addWidget(self.m_combobox_F2, 2, 2, 1, 1)
        self.label_F3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_F3.setObjectName("label_F3")
        self.layout_assignment.addWidget(self.label_F3, 3, 0, 1, 1)
        self.m_edit_F3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_edit_F3.setObjectName("m_edit_F3")
        self.layout_assignment.addWidget(self.m_edit_F3, 3, 1, 1, 1)
        self.m_combobox_F3 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_combobox_F3.sizePolicy().hasHeightForWidth())
        self.m_combobox_F3.setSizePolicy(sizePolicy)
        self.m_combobox_F3.setObjectName("m_combobox_F3")
        self.layout_assignment.addWidget(self.m_combobox_F3, 3, 2, 1, 1)
        self.label_F4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_F4.setObjectName("label_F4")
        self.layout_assignment.addWidget(self.label_F4, 4, 0, 1, 1)
        self.m_edit_F4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_edit_F4.setObjectName("m_edit_F4")
        self.layout_assignment.addWidget(self.m_edit_F4, 4, 1, 1, 1)
        self.m_combobox_F4 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_combobox_F4.sizePolicy().hasHeightForWidth())
        self.m_combobox_F4.setSizePolicy(sizePolicy)
        self.m_combobox_F4.setObjectName("m_combobox_F4")
        self.layout_assignment.addWidget(self.m_combobox_F4, 4, 2, 1, 1)
        self.label_F5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_F5.setObjectName("label_F5")
        self.layout_assignment.addWidget(self.label_F5, 5, 0, 1, 1)
        self.m_edit_F5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_edit_F5.setObjectName("m_edit_F5")
        self.layout_assignment.addWidget(self.m_edit_F5, 5, 1, 1, 1)
        self.m_combobox_F5 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_combobox_F5.sizePolicy().hasHeightForWidth())
        self.m_combobox_F5.setSizePolicy(sizePolicy)
        self.m_combobox_F5.setObjectName("m_combobox_F5")
        self.layout_assignment.addWidget(self.m_combobox_F5, 5, 2, 1, 1)
        self.label_Facies = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Facies.setFont(font)
        self.label_Facies.setObjectName("label_Facies")
        self.layout_assignment.addWidget(self.label_Facies, 0, 1, 1, 1)
        self.label_Probability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Probability.setFont(font)
        self.label_Probability.setObjectName("label_Probability")
        self.layout_assignment.addWidget(self.label_Probability, 0, 2, 1, 1)
        self.layout.addLayout(self.layout_assignment, 1, 0, 1, 1)

        self.retranslateUi(assign_probabilities)
        QtCore.QMetaObject.connectSlotsByName(assign_probabilities)

    def retranslateUi(self, assign_probabilities):
        _translate = QtCore.QCoreApplication.translate
        assign_probabilities.setWindowTitle(_translate("assign_probabilities", "Form"))
        self.Heading_label.setText(_translate("assign_probabilities", "Assign probabilities to modelled facies"))
        self.label_F1.setText(_translate("assign_probabilities", "F1"))
        self.label_F2.setText(_translate("assign_probabilities", "F2"))
        self.label_F3.setText(_translate("assign_probabilities", "F3"))
        self.label_F4.setText(_translate("assign_probabilities", "F4"))
        self.label_F5.setText(_translate("assign_probabilities", "F5"))
        self.label_Facies.setText(_translate("assign_probabilities", "Facies"))
        self.label_Probability.setText(_translate("assign_probabilities", "Probability Cube"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    assign_probabilities = QtWidgets.QWidget()
    ui = Ui_assign_probabilities()
    ui.setupUi(assign_probabilities)
    assign_probabilities.show()
    sys.exit(app.exec_())

