# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/Gaussian.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(769, 627)
        self.Gaussian_buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.Gaussian_buttonBox.setGeometry(QtCore.QRect(560, 590, 176, 27))
        self.Gaussian_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Gaussian_buttonBox.setObjectName("Gaussian_buttonBox")
        self.Trendsettings_frame = QtWidgets.QFrame(Form)
        self.Trendsettings_frame.setGeometry(QtCore.QRect(40, 330, 691, 251))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Trendsettings_frame.setPalette(palette)
        self.Trendsettings_frame.setAutoFillBackground(False)
        self.Trendsettings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Trendsettings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Trendsettings_frame.setObjectName("Trendsettings_frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.Trendsettings_frame)
        self.graphicsView.setGeometry(QtCore.QRect(420, 0, 256, 241))
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget = QtWidgets.QWidget(self.Trendsettings_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 411, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Trendsettings_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Trendsettings_label.setFont(font)
        self.Trendsettings_label.setObjectName("Trendsettings_label")
        self.gridLayout_3.addWidget(self.Trendsettings_label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.Trendsettings_kplotwidget = KPlotWidget(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Trendsettings_kplotwidget.setPalette(palette)
        self.Trendsettings_kplotwidget.setProperty("backgroundColor", QtGui.QColor(255, 255, 255))
        self.Trendsettings_kplotwidget.setProperty("foregroundColor", QtGui.QColor(0, 0, 0))
        self.Trendsettings_kplotwidget.setProperty("grid", False)
        self.Trendsettings_kplotwidget.setObjectName("Trendsettings_kplotwidget")
        self.gridLayout_3.addWidget(self.Trendsettings_kplotwidget, 1, 1, 2, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Depositionaldirection_label = QtWidgets.QLabel(self.layoutWidget)
        self.Depositionaldirection_label.setObjectName("Depositionaldirection_label")
        self.gridLayout_6.addWidget(self.Depositionaldirection_label, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.DepositionalDirection_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.DepositionalDirection_lineEdit.setObjectName("DepositionalDirection_lineEdit")
        self.gridLayout_6.addWidget(self.DepositionalDirection_lineEdit, 0, 3, 1, 1)
        self.Stackingpattern_label = QtWidgets.QLabel(self.layoutWidget)
        self.Stackingpattern_label.setObjectName("Stackingpattern_label")
        self.gridLayout_6.addWidget(self.Stackingpattern_label, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 2)
        self.Stackingpattern_kcombobox = KComboBox(self.layoutWidget)
        self.Stackingpattern_kcombobox.setObjectName("Stackingpattern_kcombobox")
        self.gridLayout_6.addWidget(self.Stackingpattern_kcombobox, 1, 3, 1, 1)
        self.StackingAngle_label = QtWidgets.QLabel(self.layoutWidget)
        self.StackingAngle_label.setObjectName("StackingAngle_label")
        self.gridLayout_6.addWidget(self.StackingAngle_label, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 2, 2, 1, 1)
        self.StackingAngle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.StackingAngle_lineEdit.setObjectName("StackingAngle_lineEdit")
        self.gridLayout_6.addWidget(self.StackingAngle_lineEdit, 2, 3, 1, 1)
        self.RelativeStDev_label = QtWidgets.QLabel(self.layoutWidget)
        self.RelativeStDev_label.setObjectName("RelativeStDev_label")
        self.gridLayout_6.addWidget(self.RelativeStDev_label, 3, 0, 1, 1)
        self.RelativeStDev_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.RelativeStDev_lineEdit.setObjectName("RelativeStDev_lineEdit")
        self.gridLayout_6.addWidget(self.RelativeStDev_lineEdit, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 3, 2, 1, 1)
        self.SimBoxthickness_label = QtWidgets.QLabel(self.layoutWidget)
        self.SimBoxthickness_label.setObjectName("SimBoxthickness_label")
        self.gridLayout_6.addWidget(self.SimBoxthickness_label, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 4, 2, 1, 1)
        self.SimBoxthickness_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.SimBoxthickness_lineEdit.setObjectName("SimBoxthickness_lineEdit")
        self.gridLayout_6.addWidget(self.SimBoxthickness_lineEdit, 4, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(360, 40, 366, 275))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.ApplyTrend_checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ApplyTrend_checkBox.setObjectName("ApplyTrend_checkBox")
        self.horizontalLayout.addWidget(self.ApplyTrend_checkBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 4, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Variogram_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Variogram_label.setFont(font)
        self.Variogram_label.setObjectName("Variogram_label")
        self.gridLayout.addWidget(self.Variogram_label, 0, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 0, 2, 1, 9)
        self.Variogrammodel_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.Variogrammodel_comboBox.setObjectName("Variogrammodel_comboBox")
        self.gridLayout.addWidget(self.Variogrammodel_comboBox, 0, 11, 1, 3)
        self.Anisotropydirections_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Anisotropydirections_label.setFont(font)
        self.Anisotropydirections_label.setObjectName("Anisotropydirections_label")
        self.gridLayout.addWidget(self.Anisotropydirections_label, 4, 0, 1, 3)
        self.Azimuth_label = QtWidgets.QLabel(self.layoutWidget1)
        self.Azimuth_label.setObjectName("Azimuth_label")
        self.gridLayout.addWidget(self.Azimuth_label, 4, 4, 1, 4)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 4, 8, 1, 5)
        self.Azimuth_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Azimuth_lineEdit.setObjectName("Azimuth_lineEdit")
        self.gridLayout.addWidget(self.Azimuth_lineEdit, 4, 13, 1, 1)
        self.Dip_label = QtWidgets.QLabel(self.layoutWidget1)
        self.Dip_label.setObjectName("Dip_label")
        self.gridLayout.addWidget(self.Dip_label, 5, 4, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 5, 6, 1, 5)
        self.Dip_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Dip_lineEdit.setObjectName("Dip_lineEdit")
        self.gridLayout.addWidget(self.Dip_lineEdit, 5, 13, 1, 1)
        self.Range_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Range_label.setFont(font)
        self.Range_label.setObjectName("Range_label")
        self.gridLayout.addWidget(self.Range_label, 9, 0, 1, 1)
        self.Parallelltoazimuth_label = QtWidgets.QLabel(self.layoutWidget1)
        self.Parallelltoazimuth_label.setObjectName("Parallelltoazimuth_label")
        self.gridLayout.addWidget(self.Parallelltoazimuth_label, 9, 1, 1, 4)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 9, 5, 1, 5)
        self.Parallelltoazimuth_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Parallelltoazimuth_lineEdit.setObjectName("Parallelltoazimuth_lineEdit")
        self.gridLayout.addWidget(self.Parallelltoazimuth_lineEdit, 9, 10, 1, 4)
        self.Normaltoazimuth_label = QtWidgets.QLabel(self.layoutWidget1)
        self.Normaltoazimuth_label.setObjectName("Normaltoazimuth_label")
        self.gridLayout.addWidget(self.Normaltoazimuth_label, 10, 1, 1, 4)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 10, 5, 1, 5)
        self.Normaltoazimuth_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Normaltoazimuth_lineEdit.setObjectName("Normaltoazimuth_lineEdit")
        self.gridLayout.addWidget(self.Normaltoazimuth_lineEdit, 10, 10, 1, 4)
        self.Vertical_label = QtWidgets.QLabel(self.layoutWidget1)
        self.Vertical_label.setObjectName("Vertical_label")
        self.gridLayout.addWidget(self.Vertical_label, 11, 1, 1, 5)
        self.Vertical_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Vertical_lineEdit.setObjectName("Vertical_lineEdit")
        self.gridLayout.addWidget(self.Vertical_lineEdit, 11, 10, 1, 4)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 8, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 7, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem18, 2, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem19, 7, 4, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem20, 6, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 4, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem22, 2, 12, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem23, 3, 2, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem24, 1, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem25, 11, 6, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 40, 269, 252))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.layoutWidget2)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.graphicsView_2)
        self.Gaussianplot_label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Gaussianplot_label.setFont(font)
        self.Gaussianplot_label.setObjectName("Gaussianplot_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Gaussianplot_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Trendsettings_label.setText(_translate("Form", "Trend settings"))
        self.label.setText(_translate("Form", "Select Trend"))
        self.Depositionaldirection_label.setText(_translate("Form", "Depositional direction"))
        self.Stackingpattern_label.setText(_translate("Form", "Stacking pattern"))
        self.StackingAngle_label.setText(_translate("Form", "Stacking Angle"))
        self.RelativeStDev_label.setText(_translate("Form", "Relative St.Dev"))
        self.SimBoxthickness_label.setText(_translate("Form", "SimBox thickness:"))
        self.ApplyTrend_checkBox.setText(_translate("Form", "Apply Trend"))
        self.Variogram_label.setText(_translate("Form", "Variogram model"))
        self.Anisotropydirections_label.setText(_translate("Form", "Anisotropy directions:"))
        self.Azimuth_label.setText(_translate("Form", "Azimuth"))
        self.Dip_label.setText(_translate("Form", "Dip"))
        self.Range_label.setText(_translate("Form", "Range:"))
        self.Parallelltoazimuth_label.setText(_translate("Form", "Parallell to azimuth"))
        self.Normaltoazimuth_label.setText(_translate("Form", "Normal to azimuth"))
        self.Vertical_label.setText(_translate("Form", "Vertical (normal to dip)"))
        self.Gaussianplot_label.setText(_translate("Form", "Gaussian"))

from kcombobox import KComboBox
from kplotwidget import KPlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

