# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/Project.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_project_selection(object):
    def setupUi(self, project_selection):
        project_selection.setObjectName("project_selection")
        project_selection.setEnabled(True)
        project_selection.resize(653, 272)
        self.tabs_project_parameter = QtWidgets.QTabWidget(project_selection)
        self.tabs_project_parameter.setGeometry(QtCore.QRect(30, 10, 611, 251))
        self.tabs_project_parameter.setObjectName("tabs_project_parameter")
        self.tab_project = QtWidgets.QWidget()
        self.tab_project.setObjectName("tab_project")
        self.layoutWidget = QtWidgets.QWidget(self.tab_project)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 591, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_project = QtWidgets.QFormLayout(self.layoutWidget)
        self.layout_project.setContentsMargins(0, 0, 0, 0)
        self.layout_project.setObjectName("layout_project")
        self.layout_mode = QtWidgets.QFormLayout()
        self.layout_mode.setObjectName("layout_mode")
        self.m_rb_experimental_mode = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_experimental_mode.setFont(font)
        self.m_rb_experimental_mode.setObjectName("m_rb_experimental_mode")
        self.layout_mode.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.m_rb_experimental_mode)
        self.m_rb_read_rms_project_file = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m_rb_read_rms_project_file.setFont(font)
        self.m_rb_read_rms_project_file.setObjectName("m_rb_read_rms_project_file")
        self.layout_mode.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.m_rb_read_rms_project_file)
        self.layout_project.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.layout_mode)
        self.layout_load_rms_project = QtWidgets.QGridLayout()
        self.layout_load_rms_project.setObjectName("layout_load_rms_project")
        self.label_location_rms_project_file = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_location_rms_project_file.setFont(font)
        self.label_location_rms_project_file.setObjectName("label_location_rms_project_file")
        self.layout_load_rms_project.addWidget(self.label_location_rms_project_file, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_load_rms_project.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_load_rms_project.addItem(spacerItem1, 0, 3, 1, 1)
        self.m_button_browse_project_file = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.m_button_browse_project_file.setFont(font)
        self.m_button_browse_project_file.setObjectName("m_button_browse_project_file")
        self.layout_load_rms_project.addWidget(self.m_button_browse_project_file, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_load_rms_project.addItem(spacerItem2, 0, 6, 1, 1)
        self.m_edit_browse_project = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_edit_browse_project.setObjectName("m_edit_browse_project")
        self.layout_load_rms_project.addWidget(self.m_edit_browse_project, 0, 5, 1, 1)
        self.layout_project.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.layout_load_rms_project)
        self.button_box_ok_cancel_project = QtWidgets.QDialogButtonBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button_box_ok_cancel_project.setFont(font)
        self.button_box_ok_cancel_project.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box_ok_cancel_project.setObjectName("button_box_ok_cancel_project")
        self.layout_project.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.button_box_ok_cancel_project)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_project.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.tabs_project_parameter.addTab(self.tab_project, "")
        self.tab_parameters = QtWidgets.QWidget()
        self.tab_parameters.setObjectName("tab_parameters")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_parameters)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 10, 451, 196))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.layout_parameters = QtWidgets.QGridLayout(self.layoutWidget1)
        self.layout_parameters.setContentsMargins(0, 0, 0, 0)
        self.layout_parameters.setObjectName("layout_parameters")
        self.m_edit_facies_parameter_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.m_edit_facies_parameter_name.setObjectName("m_edit_facies_parameter_name")
        self.layout_parameters.addWidget(self.m_edit_facies_parameter_name, 2, 2, 1, 1)
        self.label_grid_model_name = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_grid_model_name.setFont(font)
        self.label_grid_model_name.setObjectName("label_grid_model_name")
        self.layout_parameters.addWidget(self.label_grid_model_name, 1, 0, 1, 1)
        self.label_workflow_name = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_workflow_name.setFont(font)
        self.label_workflow_name.setObjectName("label_workflow_name")
        self.layout_parameters.addWidget(self.label_workflow_name, 0, 0, 1, 1)
        self.label_facies_parameter_name = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_facies_parameter_name.setFont(font)
        self.label_facies_parameter_name.setObjectName("label_facies_parameter_name")
        self.layout_parameters.addWidget(self.label_facies_parameter_name, 2, 0, 1, 1)
        self.label_zones_parameter_name = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_zones_parameter_name.setFont(font)
        self.label_zones_parameter_name.setObjectName("label_zones_parameter_name")
        self.layout_parameters.addWidget(self.label_zones_parameter_name, 3, 0, 1, 1)
        self.label_gaussian_parameter_name = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_gaussian_parameter_name.setFont(font)
        self.label_gaussian_parameter_name.setObjectName("label_gaussian_parameter_name")
        self.layout_parameters.addWidget(self.label_gaussian_parameter_name, 4, 0, 1, 1)
        self.m_edit_gaussian_parameter_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.m_edit_gaussian_parameter_name.setObjectName("m_edit_gaussian_parameter_name")
        self.layout_parameters.addWidget(self.m_edit_gaussian_parameter_name, 4, 2, 1, 1)
        self.m_edit_grid_model_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.m_edit_grid_model_name.setObjectName("m_edit_grid_model_name")
        self.layout_parameters.addWidget(self.m_edit_grid_model_name, 1, 2, 1, 1)
        self.m_edit_zones_parameter_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.m_edit_zones_parameter_name.setObjectName("m_edit_zones_parameter_name")
        self.layout_parameters.addWidget(self.m_edit_zones_parameter_name, 3, 2, 1, 1)
        self.m_edit_workflow_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.m_edit_workflow_name.setObjectName("m_edit_workflow_name")
        self.layout_parameters.addWidget(self.m_edit_workflow_name, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem4, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem5, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem6, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem7, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_parameters.addItem(spacerItem8, 0, 1, 1, 1)
        self.tabs_project_parameter.addTab(self.tab_parameters, "")

        self.retranslateUi(project_selection)
        self.tabs_project_parameter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(project_selection)

    def retranslateUi(self, project_selection):
        _translate = QtCore.QCoreApplication.translate
        project_selection.setWindowTitle(_translate("project_selection", "Load Project"))
        self.m_rb_experimental_mode.setText(_translate("project_selection", "Experimental mode"))
        self.m_rb_read_rms_project_file.setText(_translate("project_selection", "Read RMS project file"))
        self.label_location_rms_project_file.setText(_translate("project_selection", "Location RMS project file"))
        self.m_button_browse_project_file.setText(_translate("project_selection", "Browse.."))
        self.tabs_project_parameter.setTabText(self.tabs_project_parameter.indexOf(self.tab_project), _translate("project_selection", "Project"))
        self.label_grid_model_name.setText(_translate("project_selection", "Grid Model name"))
        self.label_workflow_name.setText(_translate("project_selection", "Workflow name"))
        self.label_facies_parameter_name.setText(_translate("project_selection", "Facies parameter name"))
        self.label_zones_parameter_name.setText(_translate("project_selection", "Zones parameter name"))
        self.label_gaussian_parameter_name.setText(_translate("project_selection", "Gaussian parameter name"))
        self.tabs_project_parameter.setTabText(self.tabs_project_parameter.indexOf(self.tab_parameters), _translate("project_selection", "Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    project_selection = QtWidgets.QWidget()
    ui = Ui_project_selection()
    ui.setupUi(project_selection)
    project_selection.show()
    sys.exit(app.exec_())

