# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/Selection.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 176)
        self.dockWidget = QtWidgets.QDockWidget(Form)
        self.dockWidget.setGeometry(QtCore.QRect(10, 10, 468, 148))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.SelectmodelledZones_label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SelectmodelledZones_label.setFont(font)
        self.SelectmodelledZones_label.setObjectName("SelectmodelledZones_label")
        self.horizontalLayout_6.addWidget(self.SelectmodelledZones_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.Zones_Selection_radioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Zones_Selection_radioButton.setFont(font)
        self.Zones_Selection_radioButton.setObjectName("Zones_Selection_radioButton")
        self.horizontalLayout_6.addWidget(self.Zones_Selection_radioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.SelectAll_radioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SelectAll_radioButton.setFont(font)
        self.SelectAll_radioButton.setObjectName("SelectAll_radioButton")
        self.horizontalLayout_6.addWidget(self.SelectAll_radioButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.SelectmodelledFacies_label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SelectmodelledFacies_label.setFont(font)
        self.SelectmodelledFacies_label.setObjectName("SelectmodelledFacies_label")
        self.horizontalLayout_7.addWidget(self.SelectmodelledFacies_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.SelectionFacies_RadioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SelectionFacies_RadioButton.setFont(font)
        self.SelectionFacies_RadioButton.setObjectName("SelectionFacies_RadioButton")
        self.horizontalLayout_7.addWidget(self.SelectionFacies_RadioButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.SelectAllFacies_RadioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SelectAllFacies_RadioButton.setFont(font)
        self.SelectAllFacies_RadioButton.setObjectName("SelectAllFacies_RadioButton")
        self.horizontalLayout_7.addWidget(self.SelectAllFacies_RadioButton)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
        self.Selection_Ok_Cancel_buttonBox = QtWidgets.QDialogButtonBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Selection_Ok_Cancel_buttonBox.setFont(font)
        self.Selection_Ok_Cancel_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Selection_Ok_Cancel_buttonBox.setObjectName("Selection_Ok_Cancel_buttonBox")
        self.gridLayout.addWidget(self.Selection_Ok_Cancel_buttonBox, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SelectmodelledZones_label.setText(_translate("Form", "Select modelled Zones"))
        self.Zones_Selection_radioButton.setText(_translate("Form", "Selection"))
        self.SelectAll_radioButton.setText(_translate("Form", "Select All"))
        self.SelectmodelledFacies_label.setText(_translate("Form", "Select modelled Facies"))
        self.SelectionFacies_RadioButton.setText(_translate("Form", "Selection"))
        self.SelectAllFacies_RadioButton.setText(_translate("Form", "Select All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

