# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/TruncRuleTypeBayfill.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1038, 525)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1010, 485))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Bayfill_TruncIcon_kiconbutton = KIconButton(self.layoutWidget)
        self.Bayfill_TruncIcon_kiconbutton.setObjectName("Bayfill_TruncIcon_kiconbutton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Bayfill_TruncIcon_kiconbutton)
        self.TruncationRuleBayfill_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.TruncationRuleBayfill_label.setFont(font)
        self.TruncationRuleBayfill_label.setObjectName("TruncationRuleBayfill_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.TruncationRuleBayfill_label)
        self.BayfillTuncRule_kplotwidget = KPlotWidget(self.layoutWidget)
        self.BayfillTuncRule_kplotwidget.setMinimumSize(QtCore.QSize(250, 250))
        self.BayfillTuncRule_kplotwidget.setProperty("backgroundColor", QtGui.QColor(255, 255, 255))
        self.BayfillTuncRule_kplotwidget.setProperty("foregroundColor", QtGui.QColor(0, 0, 0))
        self.BayfillTuncRule_kplotwidget.setObjectName("BayfillTuncRule_kplotwidget")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.BayfillTuncRule_kplotwidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.F1_label = QtWidgets.QLabel(self.layoutWidget)
        self.F1_label.setObjectName("F1_label")
        self.gridLayout.addWidget(self.F1_label, 3, 0, 1, 1)
        self.F2_kcombobox = KComboBox(self.layoutWidget)
        self.F2_kcombobox.setObjectName("F2_kcombobox")
        self.gridLayout.addWidget(self.F2_kcombobox, 4, 1, 1, 1)
        self.F3_kcombobox = KComboBox(self.layoutWidget)
        self.F3_kcombobox.setObjectName("F3_kcombobox")
        self.gridLayout.addWidget(self.F3_kcombobox, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 6, 1, 1)
        self.F2_label = QtWidgets.QLabel(self.layoutWidget)
        self.F2_label.setObjectName("F2_label")
        self.gridLayout.addWidget(self.F2_label, 4, 0, 1, 1)
        self.F2_Prop_lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.F2_Prop_lineEdit_2.setObjectName("F2_Prop_lineEdit_2")
        self.gridLayout.addWidget(self.F2_Prop_lineEdit_2, 4, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 7, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 5, 4, 1, 1)
        self.F3_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F3_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F3_horizontalSlider.setObjectName("F3_horizontalSlider")
        self.gridLayout.addWidget(self.F3_horizontalSlider, 5, 5, 1, 1)
        self.F1_kcombobox = KComboBox(self.layoutWidget)
        self.F1_kcombobox.setObjectName("F1_kcombobox")
        self.gridLayout.addWidget(self.F1_kcombobox, 3, 1, 1, 1)
        self.F2_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F2_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F2_horizontalSlider.setObjectName("F2_horizontalSlider")
        self.gridLayout.addWidget(self.F2_horizontalSlider, 4, 5, 1, 1)
        self.F3_label = QtWidgets.QLabel(self.layoutWidget)
        self.F3_label.setObjectName("F3_label")
        self.gridLayout.addWidget(self.F3_label, 5, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 5, 6, 1, 1)
        self.F4_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F4_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F4_horizontalSlider.setObjectName("F4_horizontalSlider")
        self.gridLayout.addWidget(self.F4_horizontalSlider, 6, 5, 1, 1)
        self.F1_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F1_Prop_lineEdit.setObjectName("F1_Prop_lineEdit")
        self.gridLayout.addWidget(self.F1_Prop_lineEdit, 3, 7, 1, 1)
        self.F3_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F3_Prop_lineEdit.setObjectName("F3_Prop_lineEdit")
        self.gridLayout.addWidget(self.F3_Prop_lineEdit, 5, 7, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 3, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 6, 4, 1, 1)
        self.F5_kcombobox = KComboBox(self.layoutWidget)
        self.F5_kcombobox.setObjectName("F5_kcombobox")
        self.gridLayout.addWidget(self.F5_kcombobox, 7, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 3, 2, 1, 1)
        self.F1_kcolorbutton = KColorButton(self.layoutWidget)
        self.F1_kcolorbutton.setObjectName("F1_kcolorbutton")
        self.gridLayout.addWidget(self.F1_kcolorbutton, 3, 3, 1, 1)
        self.F5_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F5_Prop_lineEdit.setObjectName("F5_Prop_lineEdit")
        self.gridLayout.addWidget(self.F5_Prop_lineEdit, 7, 7, 1, 1)
        self.F5_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F5_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F5_horizontalSlider.setObjectName("F5_horizontalSlider")
        self.gridLayout.addWidget(self.F5_horizontalSlider, 7, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 7, 6, 1, 1)
        self.Valuesbetween_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Valuesbetween_label.setFont(font)
        self.Valuesbetween_label.setObjectName("Valuesbetween_label")
        self.gridLayout.addWidget(self.Valuesbetween_label, 1, 7, 1, 1)
        self.Facies_label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Facies_label_2.setFont(font)
        self.Facies_label_2.setObjectName("Facies_label_2")
        self.gridLayout.addWidget(self.Facies_label_2, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 6, 6, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 7, 2, 1, 1)
        self.F4_kcombobox = KComboBox(self.layoutWidget)
        self.F4_kcombobox.setObjectName("F4_kcombobox")
        self.gridLayout.addWidget(self.F4_kcombobox, 6, 1, 1, 1)
        self.Proportions_scale_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Proportions_scale_label.setFont(font)
        self.Proportions_scale_label.setObjectName("Proportions_scale_label")
        self.gridLayout.addWidget(self.Proportions_scale_label, 2, 5, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 5, 2, 1, 1)
        self.F4_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F4_Prop_lineEdit.setObjectName("F4_Prop_lineEdit")
        self.gridLayout.addWidget(self.F4_Prop_lineEdit, 6, 7, 1, 1)
        self.F5_kcolorbutton = KColorButton(self.layoutWidget)
        self.F5_kcolorbutton.setObjectName("F5_kcolorbutton")
        self.gridLayout.addWidget(self.F5_kcolorbutton, 7, 3, 1, 1)
        self.F5_label = QtWidgets.QLabel(self.layoutWidget)
        self.F5_label.setObjectName("F5_label")
        self.gridLayout.addWidget(self.F5_label, 7, 0, 1, 1)
        self.F2_kcolorbutton = KColorButton(self.layoutWidget)
        self.F2_kcolorbutton.setObjectName("F2_kcolorbutton")
        self.gridLayout.addWidget(self.F2_kcolorbutton, 4, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 2, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 2, 6, 1, 1)
        self.F3_kcolorbutton = KColorButton(self.layoutWidget)
        self.F3_kcolorbutton.setObjectName("F3_kcolorbutton")
        self.gridLayout.addWidget(self.F3_kcolorbutton, 5, 3, 1, 1)
        self.F1_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F1_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F1_horizontalSlider.setObjectName("F1_horizontalSlider")
        self.gridLayout.addWidget(self.F1_horizontalSlider, 3, 5, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 4, 4, 1, 1)
        self.Proportions_input_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Proportions_input_label.setFont(font)
        self.Proportions_input_label.setObjectName("Proportions_input_label")
        self.gridLayout.addWidget(self.Proportions_input_label, 2, 7, 1, 1)
        self.F4_kcolorbutton = KColorButton(self.layoutWidget)
        self.F4_kcolorbutton.setObjectName("F4_kcolorbutton")
        self.gridLayout.addWidget(self.F4_kcolorbutton, 6, 3, 1, 1)
        self.F4_label = QtWidgets.QLabel(self.layoutWidget)
        self.F4_label.setObjectName("F4_label")
        self.gridLayout.addWidget(self.F4_label, 6, 0, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem19)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SF_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SF_label.setFont(font)
        self.SF_label.setObjectName("SF_label")
        self.gridLayout_2.addWidget(self.SF_label, 2, 1, 1, 1)
        self.SlantFactorFloodplain_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SlantFactorFloodplain_label.setFont(font)
        self.SlantFactorFloodplain_label.setObjectName("SlantFactorFloodplain_label")
        self.gridLayout_2.addWidget(self.SlantFactorFloodplain_label, 2, 3, 1, 2)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 2, 5, 1, 1)
        self.SF_Factor_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SF_Factor_label.setFont(font)
        self.SF_Factor_label.setObjectName("SF_Factor_label")
        self.gridLayout_2.addWidget(self.SF_Factor_label, 2, 6, 1, 1)
        self.SF_Factor_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.SF_Factor_lineEdit.setObjectName("SF_Factor_lineEdit")
        self.gridLayout_2.addWidget(self.SF_Factor_lineEdit, 2, 7, 1, 1)
        self.YSF_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.YSF_label.setFont(font)
        self.YSF_label.setObjectName("YSF_label")
        self.gridLayout_2.addWidget(self.YSF_label, 3, 1, 1, 1)
        self.SlantFactor_subbay_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SlantFactor_subbay_label.setFont(font)
        self.SlantFactor_subbay_label.setObjectName("SlantFactor_subbay_label")
        self.gridLayout_2.addWidget(self.SlantFactor_subbay_label, 3, 3, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 3, 4, 1, 2)
        self.YSF_Factor_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.YSF_Factor_label.setFont(font)
        self.YSF_Factor_label.setObjectName("YSF_Factor_label")
        self.gridLayout_2.addWidget(self.YSF_Factor_label, 3, 6, 1, 1)
        self.YSF_Factor_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.YSF_Factor_lineEdit.setObjectName("YSF_Factor_lineEdit")
        self.gridLayout_2.addWidget(self.YSF_Factor_lineEdit, 3, 7, 1, 1)
        self.BHD_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BHD_label.setFont(font)
        self.BHD_label.setObjectName("BHD_label")
        self.gridLayout_2.addWidget(self.BHD_label, 4, 1, 1, 1)
        self.SlantFactor_BHD_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SlantFactor_BHD_label.setFont(font)
        self.SlantFactor_BHD_label.setObjectName("SlantFactor_BHD_label")
        self.gridLayout_2.addWidget(self.SlantFactor_BHD_label, 4, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem22, 4, 4, 1, 2)
        self.BHD_Factor_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BHD_Factor_label.setFont(font)
        self.BHD_Factor_label.setObjectName("BHD_Factor_label")
        self.gridLayout_2.addWidget(self.BHD_Factor_label, 4, 6, 1, 1)
        self.BHD_Factor_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.BHD_Factor_lineEdit.setObjectName("BHD_Factor_lineEdit")
        self.gridLayout_2.addWidget(self.BHD_Factor_lineEdit, 4, 7, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem23, 2, 2, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem24, 3, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem25, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem26, 3, 0, 1, 1)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.gridLayout_2)
        self.TruncationRuleNonCubic_buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.TruncationRuleNonCubic_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.TruncationRuleNonCubic_buttonBox.setObjectName("TruncationRuleNonCubic_buttonBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.TruncationRuleNonCubic_buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TruncationRuleBayfill_label.setText(_translate("Form", "Truncation Rule Bayfill"))
        self.F1_label.setText(_translate("Form", "F1: FLOODPLAIN"))
        self.F2_label.setText(_translate("Form", "F2: SUBBAY"))
        self.label_3.setText(_translate("Form", "Color"))
        self.F3_label.setText(_translate("Form", "F3: WBF"))
        self.Valuesbetween_label.setText(_translate("Form", "Values between [0,1]"))
        self.Facies_label_2.setText(_translate("Form", "Facies"))
        self.Proportions_scale_label.setText(_translate("Form", "Proportions Scale"))
        self.F5_label.setText(_translate("Form", "F5: LAGOON"))
        self.Proportions_input_label.setText(_translate("Form", "Proportions input"))
        self.F4_label.setText(_translate("Form", "F4: BHD"))
        self.SF_label.setText(_translate("Form", "SF"))
        self.SlantFactorFloodplain_label.setText(_translate("Form", "Slant factor floodplain"))
        self.SF_Factor_label.setText(_translate("Form", "Factor:"))
        self.YSF_label.setText(_translate("Form", "YSF"))
        self.SlantFactor_subbay_label.setText(_translate("Form", "Slant factor subbay"))
        self.YSF_Factor_label.setText(_translate("Form", "Factor:"))
        self.BHD_label.setText(_translate("Form", "SBHD"))
        self.SlantFactor_BHD_label.setText(_translate("Form", "Slant factor Bayhead delta"))
        self.BHD_Factor_label.setText(_translate("Form", "Factor:"))
        self.label_2.setText(_translate("Form", "Slanted factor <0,1>"))
        self.label_4.setText(_translate("Form", "Facies boundary"))

from kbuttongroup import KButtonGroup
from kcolorbutton import KColorButton
from kcombobox import KComboBox
from kicondialog import KIconButton
from kplotwidget import KPlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.KButtonGroup()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

