# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/TruncRuleTypeNonCubic.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1090, 326)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 1069, 306))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.TruncationRuleNonCubic_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.TruncationRuleNonCubic_label.setFont(font)
        self.TruncationRuleNonCubic_label.setObjectName("TruncationRuleNonCubic_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TruncationRuleNonCubic_label)
        self.TruncationRuleNoenCubic_kplotwidget = KPlotWidget(self.layoutWidget)
        self.TruncationRuleNoenCubic_kplotwidget.setMinimumSize(QtCore.QSize(250, 250))
        self.TruncationRuleNoenCubic_kplotwidget.setProperty("backgroundColor", QtGui.QColor(255, 255, 255))
        self.TruncationRuleNoenCubic_kplotwidget.setProperty("foregroundColor", QtGui.QColor(0, 0, 0))
        self.TruncationRuleNoenCubic_kplotwidget.setObjectName("TruncationRuleNoenCubic_kplotwidget")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.TruncationRuleNoenCubic_kplotwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.F1_label = QtWidgets.QLabel(self.layoutWidget)
        self.F1_label.setObjectName("F1_label")
        self.gridLayout.addWidget(self.F1_label, 3, 0, 1, 1)
        self.F1_kcombobox = KComboBox(self.layoutWidget)
        self.F1_kcombobox.setObjectName("F1_kcombobox")
        self.gridLayout.addWidget(self.F1_kcombobox, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.F1_kcolorbutton = KColorButton(self.layoutWidget)
        self.F1_kcolorbutton.setObjectName("F1_kcolorbutton")
        self.gridLayout.addWidget(self.F1_kcolorbutton, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 4, 1, 1)
        self.F1_Angle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F1_Angle_lineEdit.setObjectName("F1_Angle_lineEdit")
        self.gridLayout.addWidget(self.F1_Angle_lineEdit, 3, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 6, 1, 1)
        self.F1_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F1_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F1_horizontalSlider.setObjectName("F1_horizontalSlider")
        self.gridLayout.addWidget(self.F1_horizontalSlider, 3, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 8, 1, 1)
        self.F1_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F1_Prop_lineEdit.setObjectName("F1_Prop_lineEdit")
        self.gridLayout.addWidget(self.F1_Prop_lineEdit, 3, 9, 1, 1)
        self.F2_label = QtWidgets.QLabel(self.layoutWidget)
        self.F2_label.setObjectName("F2_label")
        self.gridLayout.addWidget(self.F2_label, 4, 0, 1, 1)
        self.F2_kcombobox = KComboBox(self.layoutWidget)
        self.F2_kcombobox.setObjectName("F2_kcombobox")
        self.gridLayout.addWidget(self.F2_kcombobox, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        self.F2_kcolorbutton = KColorButton(self.layoutWidget)
        self.F2_kcolorbutton.setObjectName("F2_kcolorbutton")
        self.gridLayout.addWidget(self.F2_kcolorbutton, 4, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 4, 1, 1)
        self.F2_Angle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F2_Angle_lineEdit.setObjectName("F2_Angle_lineEdit")
        self.gridLayout.addWidget(self.F2_Angle_lineEdit, 4, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 6, 1, 1)
        self.F2_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F2_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F2_horizontalSlider.setObjectName("F2_horizontalSlider")
        self.gridLayout.addWidget(self.F2_horizontalSlider, 4, 7, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 8, 1, 1)
        self.F2_Prop_lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.F2_Prop_lineEdit_2.setObjectName("F2_Prop_lineEdit_2")
        self.gridLayout.addWidget(self.F2_Prop_lineEdit_2, 4, 9, 1, 1)
        self.F3_label = QtWidgets.QLabel(self.layoutWidget)
        self.F3_label.setObjectName("F3_label")
        self.gridLayout.addWidget(self.F3_label, 5, 0, 1, 1)
        self.F3_kcombobox = KComboBox(self.layoutWidget)
        self.F3_kcombobox.setObjectName("F3_kcombobox")
        self.gridLayout.addWidget(self.F3_kcombobox, 5, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 5, 2, 1, 1)
        self.F3_kcolorbutton = KColorButton(self.layoutWidget)
        self.F3_kcolorbutton.setObjectName("F3_kcolorbutton")
        self.gridLayout.addWidget(self.F3_kcolorbutton, 5, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 4, 1, 1)
        self.F3_Angle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F3_Angle_lineEdit.setObjectName("F3_Angle_lineEdit")
        self.gridLayout.addWidget(self.F3_Angle_lineEdit, 5, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 5, 6, 1, 1)
        self.F3_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F3_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F3_horizontalSlider.setObjectName("F3_horizontalSlider")
        self.gridLayout.addWidget(self.F3_horizontalSlider, 5, 7, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 5, 8, 1, 1)
        self.F3_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F3_Prop_lineEdit.setObjectName("F3_Prop_lineEdit")
        self.gridLayout.addWidget(self.F3_Prop_lineEdit, 5, 9, 1, 1)
        self.F4_label = QtWidgets.QLabel(self.layoutWidget)
        self.F4_label.setObjectName("F4_label")
        self.gridLayout.addWidget(self.F4_label, 6, 0, 1, 1)
        self.F4_kcombobox = KComboBox(self.layoutWidget)
        self.F4_kcombobox.setObjectName("F4_kcombobox")
        self.gridLayout.addWidget(self.F4_kcombobox, 6, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 6, 2, 1, 1)
        self.F4_kcolorbutton = KColorButton(self.layoutWidget)
        self.F4_kcolorbutton.setObjectName("F4_kcolorbutton")
        self.gridLayout.addWidget(self.F4_kcolorbutton, 6, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 6, 4, 1, 1)
        self.F4_Angle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F4_Angle_lineEdit.setObjectName("F4_Angle_lineEdit")
        self.gridLayout.addWidget(self.F4_Angle_lineEdit, 6, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 6, 6, 1, 1)
        self.F4_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F4_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F4_horizontalSlider.setObjectName("F4_horizontalSlider")
        self.gridLayout.addWidget(self.F4_horizontalSlider, 6, 7, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 6, 8, 1, 1)
        self.F4_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F4_Prop_lineEdit.setObjectName("F4_Prop_lineEdit")
        self.gridLayout.addWidget(self.F4_Prop_lineEdit, 6, 9, 1, 1)
        self.F5_label = QtWidgets.QLabel(self.layoutWidget)
        self.F5_label.setObjectName("F5_label")
        self.gridLayout.addWidget(self.F5_label, 7, 0, 1, 1)
        self.F5_kcombobox = KComboBox(self.layoutWidget)
        self.F5_kcombobox.setObjectName("F5_kcombobox")
        self.gridLayout.addWidget(self.F5_kcombobox, 7, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 7, 2, 1, 1)
        self.F5_kcolorbutton = KColorButton(self.layoutWidget)
        self.F5_kcolorbutton.setObjectName("F5_kcolorbutton")
        self.gridLayout.addWidget(self.F5_kcolorbutton, 7, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 7, 4, 1, 1)
        self.F5_Angle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F5_Angle_lineEdit.setObjectName("F5_Angle_lineEdit")
        self.gridLayout.addWidget(self.F5_Angle_lineEdit, 7, 5, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 7, 6, 1, 1)
        self.F5_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F5_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F5_horizontalSlider.setObjectName("F5_horizontalSlider")
        self.gridLayout.addWidget(self.F5_horizontalSlider, 7, 7, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 7, 8, 1, 1)
        self.F5_Prop_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F5_Prop_lineEdit.setObjectName("F5_Prop_lineEdit")
        self.gridLayout.addWidget(self.F5_Prop_lineEdit, 7, 9, 1, 1)
        self.Facies_label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Facies_label_2.setFont(font)
        self.Facies_label_2.setObjectName("Facies_label_2")
        self.gridLayout.addWidget(self.Facies_label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 5, 1, 1)
        self.Proportions_input_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Proportions_input_label.setFont(font)
        self.Proportions_input_label.setObjectName("Proportions_input_label")
        self.gridLayout.addWidget(self.Proportions_input_label, 2, 9, 1, 1)
        self.Proportions_scale_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Proportions_scale_label.setFont(font)
        self.Proportions_scale_label.setObjectName("Proportions_scale_label")
        self.gridLayout.addWidget(self.Proportions_scale_label, 2, 7, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 2, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 2, 4, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem22, 2, 6, 1, 1)
        self.TruncationRuleNonCubic_buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.TruncationRuleNonCubic_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.TruncationRuleNonCubic_buttonBox.setObjectName("TruncationRuleNonCubic_buttonBox")
        self.gridLayout.addWidget(self.TruncationRuleNonCubic_buttonBox, 8, 9, 1, 1)
        self.Valuesbetween_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Valuesbetween_label.setFont(font)
        self.Valuesbetween_label.setObjectName("Valuesbetween_label")
        self.gridLayout.addWidget(self.Valuesbetween_label, 1, 9, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem23, 2, 8, 1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.TruncationRuleIcon_kiconbutton = KIconButton(self.layoutWidget)
        self.TruncationRuleIcon_kiconbutton.setObjectName("TruncationRuleIcon_kiconbutton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.TruncationRuleIcon_kiconbutton)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TruncationRuleNonCubic_label.setText(_translate("Form", "Truncation Rule Non Cubic"))
        self.F1_label.setText(_translate("Form", "F1"))
        self.F2_label.setText(_translate("Form", "F2"))
        self.F3_label.setText(_translate("Form", "F3"))
        self.F4_label.setText(_translate("Form", "F4"))
        self.F5_label.setText(_translate("Form", "F5"))
        self.Facies_label_2.setText(_translate("Form", "Facies"))
        self.label_3.setText(_translate("Form", "Color"))
        self.label_5.setText(_translate("Form", "Angle"))
        self.Proportions_input_label.setText(_translate("Form", "Proportions input"))
        self.Proportions_scale_label.setText(_translate("Form", "Proportions Scale"))
        self.Valuesbetween_label.setText(_translate("Form", "Values between [0,1]"))
        self.TruncationRuleIcon_kiconbutton.setText(_translate("Form", "Apply overlay facies"))
        self.checkBox.setText(_translate("Form", "Applied over lay facies"))

from kbuttongroup import KButtonGroup
from kcolorbutton import KColorButton
from kcombobox import KComboBox
from kicondialog import KIconButton
from kplotwidget import KPlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.KButtonGroup()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

