# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/TruncRuleTypeA.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QtPlotAreaTruncRule_kplotwidget(object):
    def setupUi(self, QtPlotAreaTruncRule_kplotwidget):
        QtPlotAreaTruncRule_kplotwidget.setObjectName("QtPlotAreaTruncRule_kplotwidget")
        QtPlotAreaTruncRule_kplotwidget.resize(963, 357)
        self.layoutWidget = QtWidgets.QWidget(QtPlotAreaTruncRule_kplotwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 14, 922, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Icon_TruncationRuleCubic_kiconbutton = KIconButton(self.layoutWidget)
        self.Icon_TruncationRuleCubic_kiconbutton.setObjectName("Icon_TruncationRuleCubic_kiconbutton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Icon_TruncationRuleCubic_kiconbutton)
        self.TruncationRuleCubic_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.TruncationRuleCubic_label.setFont(font)
        self.TruncationRuleCubic_label.setObjectName("TruncationRuleCubic_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TruncationRuleCubic_label)
        self.TruncationRuleCubic_kplotwidget = KPlotWidget(self.layoutWidget)
        self.TruncationRuleCubic_kplotwidget.setMinimumSize(QtCore.QSize(250, 250))
        self.TruncationRuleCubic_kplotwidget.setProperty("backgroundColor", QtGui.QColor(255, 255, 255))
        self.TruncationRuleCubic_kplotwidget.setProperty("foregroundColor", QtGui.QColor(0, 0, 0))
        self.TruncationRuleCubic_kplotwidget.setObjectName("TruncationRuleCubic_kplotwidget")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.TruncationRuleCubic_kplotwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.F1_label = QtWidgets.QLabel(self.layoutWidget)
        self.F1_label.setObjectName("F1_label")
        self.gridLayout.addWidget(self.F1_label, 2, 0, 1, 1)
        self.F1_kcombobox = KComboBox(self.layoutWidget)
        self.F1_kcombobox.setObjectName("F1_kcombobox")
        self.gridLayout.addWidget(self.F1_kcombobox, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 4, 1, 1)
        self.F1_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F1_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F1_horizontalSlider.setObjectName("F1_horizontalSlider")
        self.gridLayout.addWidget(self.F1_horizontalSlider, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 6, 1, 1)
        self.F1_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F1_lineEdit.setObjectName("F1_lineEdit")
        self.gridLayout.addWidget(self.F1_lineEdit, 2, 7, 1, 1)
        self.F2_label = QtWidgets.QLabel(self.layoutWidget)
        self.F2_label.setObjectName("F2_label")
        self.gridLayout.addWidget(self.F2_label, 3, 0, 1, 1)
        self.F2_kcombobox = KComboBox(self.layoutWidget)
        self.F2_kcombobox.setObjectName("F2_kcombobox")
        self.gridLayout.addWidget(self.F2_kcombobox, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 4, 1, 1)
        self.F2_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F2_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F2_horizontalSlider.setObjectName("F2_horizontalSlider")
        self.gridLayout.addWidget(self.F2_horizontalSlider, 3, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 6, 1, 1)
        self.F2_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F2_lineEdit.setObjectName("F2_lineEdit")
        self.gridLayout.addWidget(self.F2_lineEdit, 3, 7, 1, 1)
        self.F3_label = QtWidgets.QLabel(self.layoutWidget)
        self.F3_label.setObjectName("F3_label")
        self.gridLayout.addWidget(self.F3_label, 4, 0, 1, 1)
        self.F3_kcombobox = KComboBox(self.layoutWidget)
        self.F3_kcombobox.setObjectName("F3_kcombobox")
        self.gridLayout.addWidget(self.F3_kcombobox, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 4, 1, 1)
        self.F3_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F3_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F3_horizontalSlider.setObjectName("F3_horizontalSlider")
        self.gridLayout.addWidget(self.F3_horizontalSlider, 4, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 4, 6, 1, 1)
        self.F3_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F3_lineEdit.setObjectName("F3_lineEdit")
        self.gridLayout.addWidget(self.F3_lineEdit, 4, 7, 1, 1)
        self.F4_label = QtWidgets.QLabel(self.layoutWidget)
        self.F4_label.setObjectName("F4_label")
        self.gridLayout.addWidget(self.F4_label, 5, 0, 1, 1)
        self.F4_kcombobox = KComboBox(self.layoutWidget)
        self.F4_kcombobox.setObjectName("F4_kcombobox")
        self.gridLayout.addWidget(self.F4_kcombobox, 5, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 5, 4, 1, 1)
        self.F4_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F4_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F4_horizontalSlider.setObjectName("F4_horizontalSlider")
        self.gridLayout.addWidget(self.F4_horizontalSlider, 5, 5, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 5, 6, 1, 1)
        self.F4_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F4_lineEdit.setObjectName("F4_lineEdit")
        self.gridLayout.addWidget(self.F4_lineEdit, 5, 7, 1, 1)
        self.F5_label = QtWidgets.QLabel(self.layoutWidget)
        self.F5_label.setObjectName("F5_label")
        self.gridLayout.addWidget(self.F5_label, 6, 0, 1, 1)
        self.F5_kcombobox = KComboBox(self.layoutWidget)
        self.F5_kcombobox.setObjectName("F5_kcombobox")
        self.gridLayout.addWidget(self.F5_kcombobox, 6, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 6, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 6, 4, 1, 1)
        self.F5_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.F5_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.F5_horizontalSlider.setObjectName("F5_horizontalSlider")
        self.gridLayout.addWidget(self.F5_horizontalSlider, 6, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 6, 6, 1, 1)
        self.F5_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.F5_lineEdit.setObjectName("F5_lineEdit")
        self.gridLayout.addWidget(self.F5_lineEdit, 6, 7, 1, 1)
        self.Proportionsinput_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Proportionsinput_label.setFont(font)
        self.Proportionsinput_label.setObjectName("Proportionsinput_label")
        self.gridLayout.addWidget(self.Proportionsinput_label, 1, 7, 1, 1)
        self.Valuesbetween_abel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Valuesbetween_abel.setFont(font)
        self.Valuesbetween_abel.setObjectName("Valuesbetween_abel")
        self.gridLayout.addWidget(self.Valuesbetween_abel, 0, 7, 1, 1)
        self.Color_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Color_label.setFont(font)
        self.Color_label.setObjectName("Color_label")
        self.gridLayout.addWidget(self.Color_label, 1, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 1, 4, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 1, 2, 1, 1)
        self.Facies_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Facies_label.setFont(font)
        self.Facies_label.setObjectName("Facies_label")
        self.gridLayout.addWidget(self.Facies_label, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 1, 6, 1, 1)
        self.Proportions_scale_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Proportions_scale_label.setFont(font)
        self.Proportions_scale_label.setObjectName("Proportions_scale_label")
        self.gridLayout.addWidget(self.Proportions_scale_label, 1, 5, 1, 1)
        self.TruncationRuleCubic_buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.TruncationRuleCubic_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.TruncationRuleCubic_buttonBox.setObjectName("TruncationRuleCubic_buttonBox")
        self.gridLayout.addWidget(self.TruncationRuleCubic_buttonBox, 7, 7, 1, 1)
        self.F1_kcolorbutton = KColorButton(self.layoutWidget)
        self.F1_kcolorbutton.setObjectName("F1_kcolorbutton")
        self.gridLayout.addWidget(self.F1_kcolorbutton, 2, 3, 1, 1)
        self.F2_kcolorbutton = KColorButton(self.layoutWidget)
        self.F2_kcolorbutton.setObjectName("F2_kcolorbutton")
        self.gridLayout.addWidget(self.F2_kcolorbutton, 3, 3, 1, 1)
        self.F3_kcolorbutton = KColorButton(self.layoutWidget)
        self.F3_kcolorbutton.setObjectName("F3_kcolorbutton")
        self.gridLayout.addWidget(self.F3_kcolorbutton, 4, 3, 1, 1)
        self.F4_kcolorbutton = KColorButton(self.layoutWidget)
        self.F4_kcolorbutton.setObjectName("F4_kcolorbutton")
        self.gridLayout.addWidget(self.F4_kcolorbutton, 5, 3, 1, 1)
        self.F5_kcolorbutton = KColorButton(self.layoutWidget)
        self.F5_kcolorbutton.setObjectName("F5_kcolorbutton")
        self.gridLayout.addWidget(self.F5_kcolorbutton, 6, 3, 1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)

        self.retranslateUi(QtPlotAreaTruncRule_kplotwidget)
        QtCore.QMetaObject.connectSlotsByName(QtPlotAreaTruncRule_kplotwidget)

    def retranslateUi(self, QtPlotAreaTruncRule_kplotwidget):
        _translate = QtCore.QCoreApplication.translate
        QtPlotAreaTruncRule_kplotwidget.setWindowTitle(_translate("QtPlotAreaTruncRule_kplotwidget", "Form"))
        self.Icon_TruncationRuleCubic_kiconbutton.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Apply overlay facies"))
        self.TruncationRuleCubic_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Truncation Rule Cubic"))
        self.F1_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "F1"))
        self.F2_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "F2"))
        self.F3_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "F3"))
        self.F4_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "F4"))
        self.F5_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "F5"))
        self.Proportionsinput_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Proportions input"))
        self.Valuesbetween_abel.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Values between [0,1]"))
        self.Color_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Color"))
        self.Facies_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Facies"))
        self.Proportions_scale_label.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Proportions Scale"))
        self.checkBox.setText(_translate("QtPlotAreaTruncRule_kplotwidget", "Applied overlay facies"))

from kbuttongroup import KButtonGroup
from kcolorbutton import KColorButton
from kcombobox import KComboBox
from kicondialog import KIconButton
from kplotwidget import KPlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QtPlotAreaTruncRule_kplotwidget = QtWidgets.KButtonGroup()
    ui = Ui_QtPlotAreaTruncRule_kplotwidget()
    ui.setupUi(QtPlotAreaTruncRule_kplotwidget)
    QtPlotAreaTruncRule_kplotwidget.show()
    sys.exit(app.exec_())

