# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/UpdateAPSGUI_prototype.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 934)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.APS_GUI_Faner = QtWidgets.QTabWidget(self.centralwidget)
        self.APS_GUI_Faner.setGeometry(QtCore.QRect(20, 10, 881, 781))
        self.APS_GUI_Faner.setObjectName("APS_GUI_Faner")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.layoutWidget = QtWidgets.QWidget(self.tab_general)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 4, 861, 691))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_general = QtWidgets.QGridLayout(self.layoutWidget)
        self.layout_general.setContentsMargins(0, 0, 0, 0)
        self.layout_general.setObjectName("layout_general")
        self.layout_zones = QtWidgets.QGridLayout()
        self.layout_zones.setObjectName("layout_zones")
        self.m_list_selected_zones = QtWidgets.QListWidget(self.layoutWidget)
        self.m_list_selected_zones.setObjectName("m_list_selected_zones")
        self.layout_zones.addWidget(self.m_list_selected_zones, 1, 3, 1, 1)
        self.label_zones_to_be_modeled = QtWidgets.QLabel(self.layoutWidget)
        self.label_zones_to_be_modeled.setWordWrap(True)
        self.label_zones_to_be_modeled.setObjectName("label_zones_to_be_modeled")
        self.layout_zones.addWidget(self.label_zones_to_be_modeled, 1, 0, 1, 1)
        self.label_available_zones = QtWidgets.QLabel(self.layoutWidget)
        self.label_available_zones.setObjectName("label_available_zones")
        self.layout_zones.addWidget(self.label_available_zones, 0, 1, 1, 1)
        self.m_list_available_zones = QtWidgets.QListWidget(self.layoutWidget)
        self.m_list_available_zones.setObjectName("m_list_available_zones")
        self.layout_zones.addWidget(self.m_list_available_zones, 1, 1, 1, 1)
        self.label_selected_zones = QtWidgets.QLabel(self.layoutWidget)
        self.label_selected_zones.setObjectName("label_selected_zones")
        self.layout_zones.addWidget(self.label_selected_zones, 0, 3, 1, 1)
        self.m_toggle_seperate_zone_models = QtWidgets.QCheckBox(self.layoutWidget)
        self.m_toggle_seperate_zone_models.setObjectName("m_toggle_seperate_zone_models")
        self.layout_zones.addWidget(self.m_toggle_seperate_zone_models, 0, 0, 1, 1)
        self.layout_add_remove_buttons = QtWidgets.QVBoxLayout()
        self.layout_add_remove_buttons.setObjectName("layout_add_remove_buttons")
        self.m_button_add_zone = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.m_button_add_zone.setFont(font)
        self.m_button_add_zone.setObjectName("m_button_add_zone")
        self.layout_add_remove_buttons.addWidget(self.m_button_add_zone)
        self.m_button_remove_zone = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.m_button_remove_zone.setFont(font)
        self.m_button_remove_zone.setObjectName("m_button_remove_zone")
        self.layout_add_remove_buttons.addWidget(self.m_button_remove_zone)
        self.layout_zones.addLayout(self.layout_add_remove_buttons, 1, 2, 1, 1)
        self.layout_general.addLayout(self.layout_zones, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_general.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_general.addItem(spacerItem1, 4, 0, 1, 1)
        self.layout_create = QtWidgets.QGridLayout()
        self.layout_create.setObjectName("layout_create")
        self.label_model_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_model_name.setWordWrap(True)
        self.label_model_name.setObjectName("label_model_name")
        self.layout_create.addWidget(self.label_model_name, 3, 0, 1, 1)
        self.m_combo_box_select_facies_model = QtWidgets.QComboBox(self.layoutWidget)
        self.m_combo_box_select_facies_model.setObjectName("m_combo_box_select_facies_model")
        self.layout_create.addWidget(self.m_combo_box_select_facies_model, 3, 2, 1, 1)
        self.m_edit_model_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_edit_model_name.setObjectName("m_edit_model_name")
        self.layout_create.addWidget(self.m_edit_model_name, 3, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_create.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_create.addItem(spacerItem3, 3, 3, 1, 1)
        self.label_create = QtWidgets.QLabel(self.layoutWidget)
        self.label_create.setObjectName("label_create")
        self.layout_create.addWidget(self.label_create, 0, 4, 1, 1)
        self.label_select_facies_model = QtWidgets.QLabel(self.layoutWidget)
        self.label_select_facies_model.setObjectName("label_select_facies_model")
        self.layout_create.addWidget(self.label_select_facies_model, 0, 2, 1, 1)
        self.layout_general.addLayout(self.layout_create, 1, 0, 1, 1)
        self.layout_facies = QtWidgets.QGridLayout()
        self.layout_facies.setObjectName("layout_facies")
        self.m_list_available_facies = QtWidgets.QListWidget(self.layoutWidget)
        self.m_list_available_facies.setObjectName("m_list_available_facies")
        self.layout_facies.addWidget(self.m_list_available_facies, 1, 1, 1, 1)
        self.label_selected_facies = QtWidgets.QLabel(self.layoutWidget)
        self.label_selected_facies.setObjectName("label_selected_facies")
        self.layout_facies.addWidget(self.label_selected_facies, 0, 3, 1, 1)
        self.label_available_facies = QtWidgets.QLabel(self.layoutWidget)
        self.label_available_facies.setObjectName("label_available_facies")
        self.layout_facies.addWidget(self.label_available_facies, 0, 1, 1, 1)
        self.label_facies_to_be_modelled = QtWidgets.QLabel(self.layoutWidget)
        self.label_facies_to_be_modelled.setWordWrap(True)
        self.label_facies_to_be_modelled.setObjectName("label_facies_to_be_modelled")
        self.layout_facies.addWidget(self.label_facies_to_be_modelled, 1, 0, 1, 1)
        self.m_list_selected_facies = QtWidgets.QListWidget(self.layoutWidget)
        self.m_list_selected_facies.setObjectName("m_list_selected_facies")
        self.layout_facies.addWidget(self.m_list_selected_facies, 1, 3, 1, 1)
        self.layout_add_remove_new_facies = QtWidgets.QHBoxLayout()
        self.layout_add_remove_new_facies.setObjectName("layout_add_remove_new_facies")
        self.m_button_add_new_facies = QtWidgets.QPushButton(self.layoutWidget)
        self.m_button_add_new_facies.setObjectName("m_button_add_new_facies")
        self.layout_add_remove_new_facies.addWidget(self.m_button_add_new_facies)
        spacerItem4 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_add_remove_new_facies.addItem(spacerItem4)
        self.m_button_remove_selected = QtWidgets.QPushButton(self.layoutWidget)
        self.m_button_remove_selected.setObjectName("m_button_remove_selected")
        self.layout_add_remove_new_facies.addWidget(self.m_button_remove_selected)
        self.layout_facies.addLayout(self.layout_add_remove_new_facies, 2, 3, 1, 1)
        self.m_toggle_select_facies = QtWidgets.QCheckBox(self.layoutWidget)
        self.m_toggle_select_facies.setObjectName("m_toggle_select_facies")
        self.layout_facies.addWidget(self.m_toggle_select_facies, 0, 0, 1, 1)
        self.layout_add_remove_facies = QtWidgets.QVBoxLayout()
        self.layout_add_remove_facies.setObjectName("layout_add_remove_facies")
        self.m_button_add_facies = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.m_button_add_facies.setFont(font)
        self.m_button_add_facies.setObjectName("m_button_add_facies")
        self.layout_add_remove_facies.addWidget(self.m_button_add_facies)
        self.m_button_remove_facies = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.m_button_remove_facies.setFont(font)
        self.m_button_remove_facies.setObjectName("m_button_remove_facies")
        self.layout_add_remove_facies.addWidget(self.m_button_remove_facies)
        self.layout_facies.addLayout(self.layout_add_remove_facies, 1, 2, 1, 1)
        self.layout_general.addLayout(self.layout_facies, 5, 0, 1, 1)
        self.m_rb_experimental_mode = QtWidgets.QRadioButton(self.layoutWidget)
        self.m_rb_experimental_mode.setObjectName("m_rb_experimental_mode")
        self.layout_general.addWidget(self.m_rb_experimental_mode, 0, 0, 1, 1)
        self.APS_GUI_Faner.addTab(self.tab_general, "")
        self.tab_truncation_rule = QtWidgets.QWidget()
        self.tab_truncation_rule.setObjectName("tab_truncation_rule")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_truncation_rule)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 10, 861, 721))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.layout_trunctation_rule = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.layout_trunctation_rule.setContentsMargins(0, 0, 0, 0)
        self.layout_trunctation_rule.setObjectName("layout_trunctation_rule")
        self.layout_non_cubic = QtWidgets.QGridLayout()
        self.layout_non_cubic.setObjectName("layout_non_cubic")
        self.m_button_type_II = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_II.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_II.setIcon(icon)
        self.m_button_type_II.setObjectName("m_button_type_II")
        self.layout_non_cubic.addWidget(self.m_button_type_II, 1, 1, 1, 1)
        self.m_button_type_I = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_I.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_I.setIcon(icon1)
        self.m_button_type_I.setObjectName("m_button_type_I")
        self.layout_non_cubic.addWidget(self.m_button_type_I, 1, 0, 1, 1)
        self.m_button_type_III = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_III.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeIII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_III.setIcon(icon2)
        self.m_button_type_III.setObjectName("m_button_type_III")
        self.layout_non_cubic.addWidget(self.m_button_type_III, 1, 2, 1, 1)
        self.m_button_type_V = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_V.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeVI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_V.setIcon(icon3)
        self.m_button_type_V.setObjectName("m_button_type_V")
        self.layout_non_cubic.addWidget(self.m_button_type_V, 1, 4, 1, 1)
        self.m_button_type_VI = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_VI.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_VI.setIcon(icon4)
        self.m_button_type_VI.setObjectName("m_button_type_VI")
        self.layout_non_cubic.addWidget(self.m_button_type_VI, 2, 0, 1, 1)
        self.m_button_type_IV = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_IV.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeIV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_IV.setIcon(icon5)
        self.m_button_type_IV.setObjectName("m_button_type_IV")
        self.layout_non_cubic.addWidget(self.m_button_type_IV, 1, 3, 1, 1)
        self.m_button_type_VII = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_VII.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeVIII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_VII.setIcon(icon6)
        self.m_button_type_VII.setObjectName("m_button_type_VII")
        self.layout_non_cubic.addWidget(self.m_button_type_VII, 2, 1, 1, 1)
        self.label_non_cubic = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_non_cubic.setFont(font)
        self.label_non_cubic.setObjectName("label_non_cubic")
        self.layout_non_cubic.addWidget(self.label_non_cubic, 0, 0, 1, 2)
        self.layout_trunctation_rule.addLayout(self.layout_non_cubic, 4, 0, 1, 1)
        self.layout_bayfield = QtWidgets.QGridLayout()
        self.layout_bayfield.setObjectName("layout_bayfield")
        self.m_button_bayfield = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_bayfield.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/images/figures/NonCubic_TypeVII.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_bayfield.setIcon(icon7)
        self.m_button_bayfield.setObjectName("m_button_bayfield")
        self.layout_bayfield.addWidget(self.m_button_bayfield, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_bayfield.addItem(spacerItem5, 3, 0, 1, 1)
        self.label_bayfield = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bayfield.setFont(font)
        self.label_bayfield.setObjectName("label_bayfield")
        self.layout_bayfield.addWidget(self.label_bayfield, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_bayfield.addItem(spacerItem6, 0, 0, 1, 1)
        self.layout_trunctation_rule.addLayout(self.layout_bayfield, 5, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_trunctation_rule.addItem(spacerItem7, 8, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_trunctation_rule.addItem(spacerItem8, 1, 0, 1, 1)
        self.m_button_type_customized = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_customized.setText("")
        self.m_button_type_customized.setIcon(icon7)
        self.m_button_type_customized.setObjectName("m_button_type_customized")
        self.layout_trunctation_rule.addWidget(self.m_button_type_customized, 7, 0, 1, 1)
        self.label_customized = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_customized.setFont(font)
        self.label_customized.setObjectName("label_customized")
        self.layout_trunctation_rule.addWidget(self.label_customized, 6, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_trunctation_rule.addItem(spacerItem9, 3, 0, 1, 1)
        self.layout_cubic = QtWidgets.QGridLayout()
        self.layout_cubic.setObjectName("layout_cubic")
        self.m_button_type_a = QtWidgets.QPushButton(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_button_type_a.sizePolicy().hasHeightForWidth())
        self.m_button_type_a.setSizePolicy(sizePolicy)
        self.m_button_type_a.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_a.setIcon(icon8)
        self.m_button_type_a.setIconSize(QtCore.QSize(32, 16))
        self.m_button_type_a.setObjectName("m_button_type_a")
        self.layout_cubic.addWidget(self.m_button_type_a, 2, 0, 1, 1)
        self.m_button_type_c = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_c.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_c.setIcon(icon9)
        self.m_button_type_c.setObjectName("m_button_type_c")
        self.layout_cubic.addWidget(self.m_button_type_c, 2, 2, 1, 1)
        self.m_button_type_f = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_f.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_f.setIcon(icon10)
        self.m_button_type_f.setObjectName("m_button_type_f")
        self.layout_cubic.addWidget(self.m_button_type_f, 3, 0, 1, 1)
        self.m_button_type_e = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_e.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_e.setIcon(icon11)
        self.m_button_type_e.setObjectName("m_button_type_e")
        self.layout_cubic.addWidget(self.m_button_type_e, 2, 4, 1, 1)
        self.m_button_type_d = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_d.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_d.setIcon(icon12)
        self.m_button_type_d.setObjectName("m_button_type_d")
        self.layout_cubic.addWidget(self.m_button_type_d, 2, 3, 1, 1)
        self.m_button_type_b = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_b.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_b.setIcon(icon13)
        self.m_button_type_b.setObjectName("m_button_type_b")
        self.layout_cubic.addWidget(self.m_button_type_b, 2, 1, 1, 1)
        self.m_button_type_k = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_k.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_k.setIcon(icon14)
        self.m_button_type_k.setObjectName("m_button_type_k")
        self.layout_cubic.addWidget(self.m_button_type_k, 4, 0, 1, 1)
        self.m_button_type_j = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_j.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeJ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_j.setIcon(icon15)
        self.m_button_type_j.setObjectName("m_button_type_j")
        self.layout_cubic.addWidget(self.m_button_type_j, 3, 4, 1, 1)
        self.m_button_type_h = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_h.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_h.setIcon(icon16)
        self.m_button_type_h.setObjectName("m_button_type_h")
        self.layout_cubic.addWidget(self.m_button_type_h, 3, 2, 1, 1)
        self.m_button_type_i = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_i.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_i.setIcon(icon17)
        self.m_button_type_i.setObjectName("m_button_type_i")
        self.layout_cubic.addWidget(self.m_button_type_i, 3, 3, 1, 1)
        self.m_button_type_g = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_g.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_g.setIcon(icon18)
        self.m_button_type_g.setObjectName("m_button_type_g")
        self.layout_cubic.addWidget(self.m_button_type_g, 3, 1, 1, 1)
        self.m_button_type_m = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_m.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_m.setIcon(icon19)
        self.m_button_type_m.setObjectName("m_button_type_m")
        self.layout_cubic.addWidget(self.m_button_type_m, 4, 2, 1, 1)
        self.m_button_type_p = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_p.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_p.setIcon(icon20)
        self.m_button_type_p.setObjectName("m_button_type_p")
        self.layout_cubic.addWidget(self.m_button_type_p, 5, 0, 1, 1)
        self.m_button_type_o = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_o.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_o.setIcon(icon21)
        self.m_button_type_o.setObjectName("m_button_type_o")
        self.layout_cubic.addWidget(self.m_button_type_o, 4, 4, 1, 1)
        self.m_button_type_n = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_n.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_n.setIcon(icon22)
        self.m_button_type_n.setObjectName("m_button_type_n")
        self.layout_cubic.addWidget(self.m_button_type_n, 4, 3, 1, 1)
        self.m_button_type_l = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_l.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_l.setIcon(icon23)
        self.m_button_type_l.setObjectName("m_button_type_l")
        self.layout_cubic.addWidget(self.m_button_type_l, 4, 1, 1, 1)
        self.m_button_type_r = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_r.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_r.setIcon(icon24)
        self.m_button_type_r.setObjectName("m_button_type_r")
        self.layout_cubic.addWidget(self.m_button_type_r, 5, 2, 1, 1)
        self.m_button_type_s = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_s.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_s.setIcon(icon25)
        self.m_button_type_s.setObjectName("m_button_type_s")
        self.layout_cubic.addWidget(self.m_button_type_s, 5, 3, 1, 1)
        self.m_button_type_u = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_u.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_u.setIcon(icon26)
        self.m_button_type_u.setObjectName("m_button_type_u")
        self.layout_cubic.addWidget(self.m_button_type_u, 6, 0, 1, 1)
        self.m_button_type_q = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_q.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeQ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_q.setIcon(icon27)
        self.m_button_type_q.setObjectName("m_button_type_q")
        self.layout_cubic.addWidget(self.m_button_type_q, 5, 1, 1, 1)
        self.m_button_type_t = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_t.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_t.setIcon(icon28)
        self.m_button_type_t.setObjectName("m_button_type_t")
        self.layout_cubic.addWidget(self.m_button_type_t, 5, 4, 1, 1)
        self.m_button_type_v = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_v.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_v.setIcon(icon29)
        self.m_button_type_v.setObjectName("m_button_type_v")
        self.layout_cubic.addWidget(self.m_button_type_v, 6, 1, 1, 1)
        self.m_button_type_w = QtWidgets.QPushButton(self.layoutWidget_6)
        self.m_button_type_w.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/images/images/figures/Cubic_TypeW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_button_type_w.setIcon(icon30)
        self.m_button_type_w.setObjectName("m_button_type_w")
        self.layout_cubic.addWidget(self.m_button_type_w, 6, 2, 1, 1)
        self.label_cubic = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_cubic.setFont(font)
        self.label_cubic.setObjectName("label_cubic")
        self.layout_cubic.addWidget(self.label_cubic, 0, 0, 1, 1)
        self.layout_trunctation_rule.addLayout(self.layout_cubic, 2, 0, 1, 1)
        self.layout_select_zones_and_facies = QtWidgets.QGridLayout()
        self.layout_select_zones_and_facies.setObjectName("layout_select_zones_and_facies")
        self.label_select_current_zone_and_facies = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_select_current_zone_and_facies.setWordWrap(True)
        self.label_select_current_zone_and_facies.setObjectName("label_select_current_zone_and_facies")
        self.layout_select_zones_and_facies.addWidget(self.label_select_current_zone_and_facies, 1, 0, 1, 1)
        self.label_select_facies = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_select_facies.setObjectName("label_select_facies")
        self.layout_select_zones_and_facies.addWidget(self.label_select_facies, 0, 2, 1, 1)
        self.m_list_zones = QtWidgets.QListWidget(self.layoutWidget_6)
        self.m_list_zones.setObjectName("m_list_zones")
        self.layout_select_zones_and_facies.addWidget(self.m_list_zones, 1, 1, 1, 1)
        self.m_list_facies = QtWidgets.QListWidget(self.layoutWidget_6)
        self.m_list_facies.setObjectName("m_list_facies")
        self.layout_select_zones_and_facies.addWidget(self.m_list_facies, 1, 2, 1, 1)
        self.label_select_zones = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_select_zones.setObjectName("label_select_zones")
        self.layout_select_zones_and_facies.addWidget(self.label_select_zones, 0, 1, 1, 1)
        self.layout_trunctation_rule.addLayout(self.layout_select_zones_and_facies, 0, 0, 1, 1)
        self.APS_GUI_Faner.addTab(self.tab_truncation_rule, "")
        self.tab_gaussian_random_fields = QtWidgets.QWidget()
        self.tab_gaussian_random_fields.setObjectName("tab_gaussian_random_fields")
        self.layoutWidget_12 = QtWidgets.QWidget(self.tab_gaussian_random_fields)
        self.layoutWidget_12.setGeometry(QtCore.QRect(10, 30, 859, 661))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.layout_gaussian_random_fields = QtWidgets.QGridLayout(self.layoutWidget_12)
        self.layout_gaussian_random_fields.setContentsMargins(0, 0, 0, 0)
        self.layout_gaussian_random_fields.setObjectName("layout_gaussian_random_fields")
        self.label_select_facies_grf = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_select_facies_grf.setObjectName("label_select_facies_grf")
        self.layout_gaussian_random_fields.addWidget(self.label_select_facies_grf, 0, 2, 1, 1)
        self.label_select_current_zone_and_facies_grf = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_select_current_zone_and_facies_grf.setWordWrap(True)
        self.label_select_current_zone_and_facies_grf.setObjectName("label_select_current_zone_and_facies_grf")
        self.layout_gaussian_random_fields.addWidget(self.label_select_current_zone_and_facies_grf, 1, 0, 1, 1)
        self.label_select_zones_grf = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_select_zones_grf.setObjectName("label_select_zones_grf")
        self.layout_gaussian_random_fields.addWidget(self.label_select_zones_grf, 0, 1, 1, 1)
        self.group_grf_3 = QtWidgets.QGridLayout()
        self.group_grf_3.setObjectName("group_grf_3")
        self.label_GRF3 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF3.setFont(font)
        self.label_GRF3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF3.setObjectName("label_GRF3")
        self.group_grf_3.addWidget(self.label_GRF3, 0, 0, 1, 1)
        self.m_button_GRF3_settings = QtWidgets.QPushButton(self.layoutWidget_12)
        self.m_button_GRF3_settings.setObjectName("m_button_GRF3_settings")
        self.group_grf_3.addWidget(self.m_button_GRF3_settings, 0, 2, 1, 1)
        self.m_toggle_GRF3 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.m_toggle_GRF3.setObjectName("m_toggle_GRF3")
        self.group_grf_3.addWidget(self.m_toggle_GRF3, 1, 2, 1, 1)
        self.m_plot_area_GRF3 = QCustomPlot(self.layoutWidget_12)
        self.m_plot_area_GRF3.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_area_GRF3.setObjectName("m_plot_area_GRF3")
        self.group_grf_3.addWidget(self.m_plot_area_GRF3, 0, 1, 2, 1)
        self.layout_gaussian_random_fields.addLayout(self.group_grf_3, 3, 1, 1, 1)
        self.m_list_facies_grf = QtWidgets.QListWidget(self.layoutWidget_12)
        self.m_list_facies_grf.setObjectName("m_list_facies_grf")
        self.layout_gaussian_random_fields.addWidget(self.m_list_facies_grf, 1, 2, 1, 1)
        self.group_grf_4 = QtWidgets.QGridLayout()
        self.group_grf_4.setObjectName("group_grf_4")
        self.label_GRF4 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF4.setFont(font)
        self.label_GRF4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF4.setObjectName("label_GRF4")
        self.group_grf_4.addWidget(self.label_GRF4, 0, 0, 1, 1)
        self.m_button_GRF4_settings = QtWidgets.QPushButton(self.layoutWidget_12)
        self.m_button_GRF4_settings.setObjectName("m_button_GRF4_settings")
        self.group_grf_4.addWidget(self.m_button_GRF4_settings, 0, 2, 1, 1)
        self.m_toggle_GRF4 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.m_toggle_GRF4.setObjectName("m_toggle_GRF4")
        self.group_grf_4.addWidget(self.m_toggle_GRF4, 1, 2, 1, 1)
        self.m_plot_area_GRF4 = QCustomPlot(self.layoutWidget_12)
        self.m_plot_area_GRF4.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_area_GRF4.setObjectName("m_plot_area_GRF4")
        self.group_grf_4.addWidget(self.m_plot_area_GRF4, 0, 1, 2, 1)
        self.layout_gaussian_random_fields.addLayout(self.group_grf_4, 3, 2, 1, 1)
        self.group_grf_2 = QtWidgets.QGridLayout()
        self.group_grf_2.setObjectName("group_grf_2")
        self.m_plot_area_GRF2 = QtWidgets.QFrame(self.layoutWidget_12)
        self.m_plot_area_GRF2.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_area_GRF2.setProperty("backgroundColor", QtGui.QColor(255, 255, 255))
        self.m_plot_area_GRF2.setProperty("foregroundColor", QtGui.QColor(0, 0, 0))
        self.m_plot_area_GRF2.setObjectName("m_plot_area_GRF2")
        self.group_grf_2.addWidget(self.m_plot_area_GRF2, 0, 1, 2, 1)
        self.label_GRF2 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF2.setFont(font)
        self.label_GRF2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF2.setObjectName("label_GRF2")
        self.group_grf_2.addWidget(self.label_GRF2, 0, 0, 1, 1)
        self.m_button_GRF2_settings = QtWidgets.QPushButton(self.layoutWidget_12)
        self.m_button_GRF2_settings.setObjectName("m_button_GRF2_settings")
        self.group_grf_2.addWidget(self.m_button_GRF2_settings, 0, 2, 1, 1)
        self.m_toggle_GRF2 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.m_toggle_GRF2.setObjectName("m_toggle_GRF2")
        self.group_grf_2.addWidget(self.m_toggle_GRF2, 1, 2, 1, 1)
        self.layout_gaussian_random_fields.addLayout(self.group_grf_2, 2, 2, 1, 1)
        self.m_list_zones_grf = QtWidgets.QListWidget(self.layoutWidget_12)
        self.m_list_zones_grf.setObjectName("m_list_zones_grf")
        self.layout_gaussian_random_fields.addWidget(self.m_list_zones_grf, 1, 1, 1, 1)
        self.group_grf_1 = QtWidgets.QGridLayout()
        self.group_grf_1.setObjectName("group_grf_1")
        self.m_plot_area_GRF1 = QtWidgets.QFrame(self.layoutWidget_12)
        self.m_plot_area_GRF1.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_area_GRF1.setProperty("backgroundColor", QtGui.QColor(255, 255, 255))
        self.m_plot_area_GRF1.setProperty("foregroundColor", QtGui.QColor(0, 0, 0))
        self.m_plot_area_GRF1.setObjectName("m_plot_area_GRF1")
        self.group_grf_1.addWidget(self.m_plot_area_GRF1, 0, 1, 2, 1)
        self.m_button_GRF1_settings = QtWidgets.QPushButton(self.layoutWidget_12)
        self.m_button_GRF1_settings.setObjectName("m_button_GRF1_settings")
        self.group_grf_1.addWidget(self.m_button_GRF1_settings, 0, 2, 1, 1)
        self.m_toggle_GRF1 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.m_toggle_GRF1.setObjectName("m_toggle_GRF1")
        self.group_grf_1.addWidget(self.m_toggle_GRF1, 1, 2, 1, 1)
        self.label_GRF1 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF1.setFont(font)
        self.label_GRF1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF1.setObjectName("label_GRF1")
        self.group_grf_1.addWidget(self.label_GRF1, 0, 0, 1, 1)
        self.layout_gaussian_random_fields.addLayout(self.group_grf_1, 2, 1, 1, 1)
        self.group_grf_5 = QtWidgets.QGridLayout()
        self.group_grf_5.setObjectName("group_grf_5")
        self.label_GRF5 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF5.setFont(font)
        self.label_GRF5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF5.setObjectName("label_GRF5")
        self.group_grf_5.addWidget(self.label_GRF5, 0, 0, 1, 1)
        self.m_button_GRF5_settings = QtWidgets.QPushButton(self.layoutWidget_12)
        self.m_button_GRF5_settings.setObjectName("m_button_GRF5_settings")
        self.group_grf_5.addWidget(self.m_button_GRF5_settings, 0, 2, 1, 1)
        self.m_toggle_GRF5 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.m_toggle_GRF5.setObjectName("m_toggle_GRF5")
        self.group_grf_5.addWidget(self.m_toggle_GRF5, 1, 2, 1, 1)
        self.m_plot_area_GRF5 = QCustomPlot(self.layoutWidget_12)
        self.m_plot_area_GRF5.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_area_GRF5.setObjectName("m_plot_area_GRF5")
        self.group_grf_5.addWidget(self.m_plot_area_GRF5, 0, 1, 2, 1)
        self.layout_gaussian_random_fields.addLayout(self.group_grf_5, 4, 1, 1, 1)
        self.group_grf_6 = QtWidgets.QGridLayout()
        self.group_grf_6.setObjectName("group_grf_6")
        self.m_plot_area_GRF6 = QtWidgets.QFrame(self.layoutWidget_12)
        self.m_plot_area_GRF6.setMinimumSize(QtCore.QSize(180, 180))
        self.m_plot_area_GRF6.setProperty("backgroundColor", QtGui.QColor(255, 255, 255))
        self.m_plot_area_GRF6.setProperty("foregroundColor", QtGui.QColor(0, 0, 0))
        self.m_plot_area_GRF6.setObjectName("m_plot_area_GRF6")
        self.group_grf_6.addWidget(self.m_plot_area_GRF6, 0, 1, 2, 1)
        self.label_GRF6 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GRF6.setFont(font)
        self.label_GRF6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GRF6.setObjectName("label_GRF6")
        self.group_grf_6.addWidget(self.label_GRF6, 0, 0, 1, 1)
        self.m_button_GRF6_settings = QtWidgets.QPushButton(self.layoutWidget_12)
        self.m_button_GRF6_settings.setObjectName("m_button_GRF6_settings")
        self.group_grf_6.addWidget(self.m_button_GRF6_settings, 0, 2, 1, 1)
        self.m_toggle_GRF6 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.m_toggle_GRF6.setObjectName("m_toggle_GRF6")
        self.group_grf_6.addWidget(self.m_toggle_GRF6, 1, 2, 1, 1)
        self.layout_gaussian_random_fields.addLayout(self.group_grf_6, 4, 2, 1, 1)
        self.APS_GUI_Faner.addTab(self.tab_gaussian_random_fields, "")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 800, 871, 83))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.layout_button_group = QtWidgets.QGridLayout(self.layoutWidget1)
        self.layout_button_group.setContentsMargins(0, 0, 0, 0)
        self.layout_button_group.setObjectName("layout_button_group")
        self.m_button_previewer = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.m_button_previewer.setFont(font)
        self.m_button_previewer.setObjectName("m_button_previewer")
        self.layout_button_group.addWidget(self.m_button_previewer, 1, 5, 1, 1)
        self.m_button_close = QtWidgets.QPushButton(self.layoutWidget1)
        self.m_button_close.setObjectName("m_button_close")
        self.layout_button_group.addWidget(self.m_button_close, 1, 8, 1, 1)
        self.m_button_save = QtWidgets.QPushButton(self.layoutWidget1)
        self.m_button_save.setObjectName("m_button_save")
        self.layout_button_group.addWidget(self.m_button_save, 1, 6, 1, 1)
        self.m_button_assign_probability = QtWidgets.QPushButton(self.layoutWidget1)
        self.m_button_assign_probability.setObjectName("m_button_assign_probability")
        self.layout_button_group.addWidget(self.m_button_assign_probability, 0, 8, 1, 1)
        self.m_toggle_condition_to_wells = QtWidgets.QCheckBox(self.layoutWidget1)
        self.m_toggle_condition_to_wells.setObjectName("m_toggle_condition_to_wells")
        self.layout_button_group.addWidget(self.m_toggle_condition_to_wells, 0, 5, 1, 1)
        self.m_button_save_as = QtWidgets.QPushButton(self.layoutWidget1)
        self.m_button_save_as.setObjectName("m_button_save_as")
        self.layout_button_group.addWidget(self.m_button_save_as, 1, 7, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Recent_files = QtWidgets.QAction(MainWindow)
        self.action_Recent_files.setObjectName("action_Recent_files")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Save_As = QtWidgets.QAction(MainWindow)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_Save_As_Template = QtWidgets.QAction(MainWindow)
        self.action_Save_As_Template.setObjectName("action_Save_As_Template")
        self.action_Close = QtWidgets.QAction(MainWindow)
        self.action_Close.setObjectName("action_Close")
        self.action_Read_RMS_Project_File = QtWidgets.QAction(MainWindow)
        self.action_Read_RMS_Project_File.setObjectName("action_Read_RMS_Project_File")
        self.action_Experimental_Mode = QtWidgets.QAction(MainWindow)
        self.action_Experimental_Mode.setObjectName("action_Experimental_Mode")
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Recent_files)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Save_As)
        self.menu_File.addAction(self.action_Save_As_Template)
        self.menu_File.addAction(self.action_Close)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.APS_GUI_Faner.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_zones_to_be_modeled.setText(_translate("MainWindow", "Zone(s) to be modelled       "))
        self.label_available_zones.setText(_translate("MainWindow", "Zones selection:"))
        self.label_selected_zones.setText(_translate("MainWindow", "Selected Zones:"))
        self.m_toggle_seperate_zone_models.setText(_translate("MainWindow", "Seperate Zone Models"))
        self.m_button_add_zone.setText(_translate("MainWindow", ">"))
        self.m_button_remove_zone.setText(_translate("MainWindow", "<"))
        self.label_model_name.setText(_translate("MainWindow", "Output Facies Model Name"))
        self.label_create.setText(_translate("MainWindow", "Create"))
        self.label_select_facies_model.setText(_translate("MainWindow", "Select Facies Model"))
        self.label_selected_facies.setText(_translate("MainWindow", "Simulated facies"))
        self.label_available_facies.setText(_translate("MainWindow", "Available Facies "))
        self.label_facies_to_be_modelled.setText(_translate("MainWindow", "Facies to be modelled         "))
        self.m_button_add_new_facies.setText(_translate("MainWindow", "Add..."))
        self.m_button_remove_selected.setText(_translate("MainWindow", "Remove added"))
        self.m_toggle_select_facies.setText(_translate("MainWindow", "Select Facies"))
        self.m_button_add_facies.setText(_translate("MainWindow", ">"))
        self.m_button_remove_facies.setText(_translate("MainWindow", "<"))
        self.m_rb_experimental_mode.setText(_translate("MainWindow", "Experimental Mode"))
        self.APS_GUI_Faner.setTabText(self.APS_GUI_Faner.indexOf(self.tab_general), _translate("MainWindow", "General"))
        self.label_non_cubic.setText(_translate("MainWindow", "Non-Cubic"))
        self.label_bayfield.setText(_translate("MainWindow", "Bayfill"))
        self.label_customized.setText(_translate("MainWindow", "Customized "))
        self.label_cubic.setText(_translate("MainWindow", "Cubic"))
        self.label_select_current_zone_and_facies.setText(_translate("MainWindow", "Select current zone and facies"))
        self.label_select_facies.setText(_translate("MainWindow", "Selected Facies"))
        self.label_select_zones.setText(_translate("MainWindow", "Zones selection"))
        self.APS_GUI_Faner.setTabText(self.APS_GUI_Faner.indexOf(self.tab_truncation_rule), _translate("MainWindow", "Truncation Rule"))
        self.label_select_facies_grf.setText(_translate("MainWindow", "Selected Facies"))
        self.label_select_current_zone_and_facies_grf.setText(_translate("MainWindow", "Select current zone and facies"))
        self.label_select_zones_grf.setText(_translate("MainWindow", "Zones selection"))
        self.label_GRF3.setText(_translate("MainWindow", "GRF3"))
        self.m_button_GRF3_settings.setText(_translate("MainWindow", "GRF3 Settings"))
        self.m_toggle_GRF3.setText(_translate("MainWindow", "GRF3 Applied"))
        self.label_GRF4.setText(_translate("MainWindow", "GRF4"))
        self.m_button_GRF4_settings.setText(_translate("MainWindow", "GRF4 Settings"))
        self.m_toggle_GRF4.setText(_translate("MainWindow", "GRF4 Applied"))
        self.label_GRF2.setText(_translate("MainWindow", "GRF2"))
        self.m_button_GRF2_settings.setText(_translate("MainWindow", "GRF2 Settings"))
        self.m_toggle_GRF2.setText(_translate("MainWindow", "GRF2 Applied"))
        self.m_button_GRF1_settings.setText(_translate("MainWindow", "GRF1 Settings"))
        self.m_toggle_GRF1.setText(_translate("MainWindow", "GRF1 Applied"))
        self.label_GRF1.setText(_translate("MainWindow", "GRF1"))
        self.label_GRF5.setText(_translate("MainWindow", "GRF5"))
        self.m_button_GRF5_settings.setText(_translate("MainWindow", "GRF5 Settings"))
        self.m_toggle_GRF5.setText(_translate("MainWindow", "GRF5 Applied"))
        self.label_GRF6.setText(_translate("MainWindow", "GRF6"))
        self.m_button_GRF6_settings.setText(_translate("MainWindow", "GRF6 Settings"))
        self.m_toggle_GRF6.setText(_translate("MainWindow", "GRF6 Applied"))
        self.APS_GUI_Faner.setTabText(self.APS_GUI_Faner.indexOf(self.tab_gaussian_random_fields), _translate("MainWindow", "GRF"))
        self.m_button_previewer.setText(_translate("MainWindow", "Run Previewer"))
        self.m_button_close.setText(_translate("MainWindow", "Close"))
        self.m_button_save.setText(_translate("MainWindow", "Save"))
        self.m_button_assign_probability.setText(_translate("MainWindow", "Assign Probability Cube"))
        self.m_toggle_condition_to_wells.setText(_translate("MainWindow", "Condition to wells"))
        self.m_button_save_as.setText(_translate("MainWindow", "Save As.."))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Recent_files.setText(_translate("MainWindow", "&Recent files"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save_As.setText(_translate("MainWindow", "&Save As"))
        self.action_Save_As_Template.setText(_translate("MainWindow", "&Save As Template"))
        self.action_Close.setText(_translate("MainWindow", "&Close"))
        self.action_Read_RMS_Project_File.setText(_translate("MainWindow", "&Read RMS Project File"))
        self.action_Experimental_Mode.setText(_translate("MainWindow", "&Experimental Mode"))

from qcustomplot import QCustomPlot
from src.resources import Resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

