site_name: APS Documentation
docs_dir: aps-user-guide
repo_url: https://github.com/equinor/APS-Facies
repo_name: equinor/APS-Facies

nav:
  - README.md
  - Define APS Job:
      - define-aps-job/README.md
      - define-aps-job/select-grid-model/README.md
      - define-aps-job/choose-name-of-facies-realization/README.md
      - Select zone:
          - define-aps-job/select-zone/README.md
          - define-aps-job/select-zone/select-bw/README.md
          - define-aps-job/select-zone/select-facies-log/README.md
          - define-aps-job/select-zone/specify-facies-probabilities/README.md
          - Select type of truncation:
              - define-aps-job/select-zone/select-type-of-truncation/README.md
              - define-aps-job/select-zone/select-type-of-truncation/cubic/README.md
              - define-aps-job/select-zone/select-type-of-truncation/non-cubic/README.md
              - define-aps-job/select-zone/select-type-of-truncation/bayfill/README.md
              - Overlay facies rule:
                  - define-aps-job/select-zone/select-type-of-truncation/overlay-facies-rule/README.md
                  - define-aps-job/select-zone/select-type-of-truncation/overlay-facies-rule/select-background-facies/README.md
                  - define-aps-job/select-zone/select-type-of-truncation/overlay-facies-rule/select-grf/README.md
                  - define-aps-job/select-zone/select-type-of-truncation/overlay-facies-rule/select-facies/README.md
          - Specify Gaussian Random Fields:
              - define-aps-job/select-zone/specify-gaussian-random-fields/README.md
              - define-aps-job/select-zone/specify-gaussian-random-fields/set-parameters-for-simulating-grf/README.md
              - define-aps-job/select-zone/specify-gaussian-random-fields/add-trend/README.md
      - Job setting:
          - define-aps-job/job-setting/README.md
          - Select mode:
              - define-aps-job/job-setting/select-mode/README.md
              - define-aps-job/job-setting/select-mode/ordinary-mode/README.md
              - define-aps-job/job-setting/select-mode/fmu-uncertainty-parameter-mode/README.md
              - define-aps-job/job-setting/select-mode/fmu-assisted-history-matching-mode/README.md
          - define-aps-job/job-setting/log-setting/README.md
          - define-aps-job/job-setting/transformation-setting/README.md
          - define-aps-job/job-setting/probability-check-setting/README.md
          - define-aps-job/job-setting/non-standard-fmu-setting/README.md
          - define-aps-job/job-setting/preview-related-settings/README.md
          - define-aps-job/job-setting/generate-files-for-fmu-ert-configuration/README.md
      - define-aps-job/preview/README.md
  - configuration-of-aps-with-ahm-using-ert/README.md
  - APS algorithm:
      - aps-algorithm/README.md
      - aps-algorithm/implementation/README.md
  - Prepare facies probabilities:
      - prepare-facies-probabilities/README.md
      - Probability logs:
          - prepare-facies-probabilities/probability-logs/README.md
          - Facies log:
              - prepare-facies-probabilities/probability-logs/facies-log/README.md
          - prepare-facies-probabilities/probability-logs/conditional-probabilities-given-facies/README.md
      - Probability trends:
          - prepare-facies-probabilities/probability-trends/README.md
          - Trends from seismic data:
              - prepare-facies-probabilities/probability-trends/trends-from-seismic-data/README.md
          - prepare-facies-probabilities/probability-trends/trends-from-geological-interpretations/README.md
      - Conditioned probability cubes:
          - prepare-facies-probabilities/conditioned-probability-cubes/README.md
          - prepare-facies-probabilities/conditioned-probability-cubes/rms-petrosim-to-condition-3d-probability-parameters/README.md
      - prepare-facies-probabilities/normalisation/README.md
  - APS toolbox:
      - aps-toolbox/README.md
      - aps-toolbox/probability-logs/README.md
      - aps-toolbox/probability-trends/README.md
      - aps-toolbox/redefine-or-merge-blocked-well-facies-logs/README.md
      - aps-toolbox/convert-bitmap-to-rms-surface-format/README.md
      - aps-toolbox/check-normalisation-of-facies-probabilities/README.md
      - aps-toolbox/copy-3d-parameters-to-or-from-ertbox/README.md
  - APS model file format:
      - aps-model-file-format/README.md
  - Mind Manager map: mind-manager/index.html

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - sane_lists

  # For MathJax
  - pymdownx.arithmatex:
      generic: true

  # Abbreviation
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  # Icons and emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Definitions
  - def_list

# MathJax
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - 'assets/stylesheets/mkdocs-eq.css'
  - 'https://cdn.eds.equinor.com/font/equinor-font.css'

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

watch:
  - includes
