on:
  workflow_call:
    inputs:
      stable:
        type: boolean
        default: false
        description: 'Toggles whether a stable (full release) or a beta should be build'

jobs:
  build-gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-python-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: gui/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('gui/yarn.lock', 'gui/package.json') }}

      - name: Set up dependencies
        run: |
          if [[ ! -d .venv ]]; then
            uv sync --no-install-project
          fi

      - name: Initialize project
        run: |
          source .venv/bin/activate
          make --directory=${{ github.workspace }} init

      - name: Build GUI
        run: |
          source .venv/bin/activate
          export NODE_OPTIONS=--max_old_space_size=4096
          make --directory=${{ github.workspace }} ${{ inputs.stable && 'build-stable-gui' || 'build-gui' }}

      - name: Store GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-gui
          path: |
            *.plugin
          retention-days: 90
          compression-level: '0' # The plugin is already a zip file, so we don't need to compress it again

      - name: Store metadata about the build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-metadata
          path: |
            DEPLOY_VERSION.txt
