name: "Push to develop/master branch"
# This workflow should only build artifacts to be used,
# it does not concern itself with checking if the code works.
# `on-push-other-branches.yaml` does that.

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master

jobs:
  on-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up dependencies
        run: |
          python3.8 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install "poetry==1.4.0"
          poetry install
          make --directory=${{ github.workspace }} init

      - name: Build GUI
        run: |
          source .venv/bin/activate
          export NODE_OPTIONS=--max_old_space_size=4096
          make --directory=${{ github.workspace }} build-gui

      - name: Store GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: gui
          path: |
            *.plugin
          retention-days: 400
