name: 'Build and test the GUI'
# This workflow should only test that the pushed code works well.
# Consider it a quality check workflow.

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - uses: pre-commit/action@v3.0.1

  build-gui:
    uses: ./.github/workflows/build-plugin.yaml
