name: 'Build and test the GUI'
# This workflow should only test that the pushed code works well.
# Consider it a quality check workflow.

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --all-files --show-diff-on-failure --color=always
        shell: bash

  build-gui:
    uses: ./.github/workflows/build-plugin.yaml
