name: "Create a new release"

on:
  push:
    tags:
      - v*

jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up dependencies
        run: |
          python3.8 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install "poetry==1.4.0"
          poetry install
          make --directory=${{ github.workspace }} init

      - name: Build GUI
        run: |
          source .venv/bin/activate
          make --directory=${{ github.workspace }} build-stable-gui

      - name: version
        run: echo "::set-output name=version::$(make print-APS_VERSION)"
        id: version

      - name: Changelog content
        run: echo "::set-output name=body::$(sed -n '/## ${{ steps.version.outputs.version }}/,/^## /p' CHANGELOG.md | sed '$d')"
        id: body

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.version.outputs.version }}
          body: ${{ steps.body.outputs.body }}
          artifacts: "*.plugin"
